// backend/src/services/internalProvider/base/providerId.service.ts

import { ulid } from "ulid";

/**
 * ------------------------------------------------------------------
 * STHN Internal Provider Platform
 * Provider ID Service
 * ------------------------------------------------------------------
 *
 * Generates all provider-side identifiers.
 *
 * This service is intentionally stateless and has no dependencies.
 *
 * Every identifier generated by this service is globally unique,
 * lexicographically sortable, and safe for external exposure.
 * ------------------------------------------------------------------
 */
export class ProviderIdService {
  /**
   * Generate a provider payment identifier.
   */
  generatePaymentId(): string {
    return this.generate("pay");
  }

  /**
   * Generate a provider refund identifier.
   */
  generateRefundId(): string {
    return this.generate("ref");
  }

  /**
   * Generate a provider settlement identifier.
   */
  generateSettlementId(): string {
    return this.generate("set");
  }

  /**
   * Generate a provider payout identifier.
   */
  generatePayoutId(): string {
    return this.generate("pout");
  }

  /** Generate a provider-side payout completion transaction identifier. */
  generatePayoutTransactionId(): string {
    return this.generate("ptxn");
  }

  /**
   * Generate a provider webhook identifier.
   */
  generateWebhookId(): string {
    return this.generate("wh");
  }

  /**
   * Generate a provider reference.
   */
  generateProviderReference(): string {
    return this.generate("pref");
  }

  /**
   * Generate a correlation identifier.
   */
  generateCorrelationId(): string {
    return this.generate("corr");
  }

  /**
   * Generate a request identifier.
   */
  generateRequestId(): string {
    return this.generate("req");
  }

  /**
   * Generate an identifier using the supplied prefix.
   */
  private generate(prefix: string): string {
    return `${prefix}_${ulid()}`;
  }
}

export default new ProviderIdService();
