export enum BookingTerminationType {
  CUSTOMER_CANCELLED = "CUSTOMER_CANCELLED",
  CREATOR_REJECTED = "CREATOR_REJECTED",
  CREATOR_CANCELLED = "CREATOR_CANCELLED",
  BOOKING_EXPIRED = "BOOKING_EXPIRED",
  ADMIN_CANCELLED = "ADMIN_CANCELLED",
  GOVERNANCE_TERMINATED = "GOVERNANCE_TERMINATED",
  SYSTEM_TERMINATED = "SYSTEM_TERMINATED",
}

export enum BookingTerminationActorType {
  CUSTOMER = "CUSTOMER",
  CREATOR = "CREATOR",
  ADMIN = "ADMIN",
  GOVERNANCE = "GOVERNANCE",
  SYSTEM = "SYSTEM",
}
