import mongoose, { Types } from "mongoose";
import {
  ProviderEntityType,
  ProviderEventType,
  ProviderOperation,
  ProviderSimulationMode,
} from "../../constants/internalProvider";
import { InternalTopUpFundingOutcome } from "../../enums/financial/internalTopUpFundingOutcome.enum";
import { InternalTopUpFundingFailureCode } from "../../enums/financial/internalTopUpFundingFailureCode.enum";
import { InternalTopUpFundingStatus } from "../../enums/financial/internalTopUpFundingStatus.enum";
import { InternalTopUpFundingError } from "../../errors/financial/InternalTopUpFundingError";
import { generateFinancialReference } from "../../utils/financial/reference.util";
import { internalTopUpFundingRepository } from "../../repositories/internalTopUpFunding.repository";
import { IInternalTopUpFunding } from "../../models/internalTopUpFunding.model";
import ProviderEventService from "../internalProvider/events/providerEvent.service";

type Creation = { topUpRequestId: Types.ObjectId; topUpReference: string; amount: number; currency: any; idempotencyKey: string; requestFingerprint: string };
export class InternalTopUpFundingService {
  private normalize(outcome: InternalTopUpFundingOutcome, code?: InternalTopUpFundingFailureCode, reason?: unknown) {
    if (!Object.values(InternalTopUpFundingOutcome).includes(outcome)) throw new InternalTopUpFundingError("Invalid provider funding outcome.", "INTERNAL_TOP_UP_FUNDING_INVALID_OUTCOME", 400);
    if (outcome === InternalTopUpFundingOutcome.SUCCESS) { if (code !== undefined || reason !== undefined) throw new InternalTopUpFundingError("Success cannot include failure data.", "INTERNAL_TOP_UP_FUNDING_FAILURE_DATA_NOT_ALLOWED", 400); return {}; }
    if (!Object.values(InternalTopUpFundingFailureCode).includes(code as InternalTopUpFundingFailureCode)) throw new InternalTopUpFundingError("A valid failure code is required.", "INTERNAL_TOP_UP_FUNDING_FAILURE_CODE_REQUIRED", 400);
    if (reason !== undefined && typeof reason !== "string") throw new InternalTopUpFundingError("Failure reason is invalid.", "INTERNAL_TOP_UP_FUNDING_INVALID_FAILURE_REASON", 400);
    const failureReason = typeof reason === "string" ? reason.trim() : undefined;
    if (typeof reason === "string" && (!failureReason || failureReason.length > 500)) throw new InternalTopUpFundingError("Failure reason is invalid.", "INTERNAL_TOP_UP_FUNDING_INVALID_FAILURE_REASON", 400);
    return { failureCode: code as InternalTopUpFundingFailureCode, failureReason };
  }
  private async event(funding: IInternalTopUpFunding, eventType: ProviderEventType, operation: ProviderOperation, session: mongoose.ClientSession) { await ProviderEventService.recordEvent({ entityType: ProviderEntityType.TOP_UP_FUNDING, entityId: funding._id as Types.ObjectId, eventType, operation, transitionKey: `${funding.fundingReference}:${eventType}`, providerEntityId: funding.fundingReference, providerMetadata: { provider: "INTERNAL", environment: process.env.NODE_ENV ?? "development", simulationMode: ProviderSimulationMode.ADMIN_OVERRIDE } as any, execution: { attemptNumber: 1, retryCount: 0, isTestMode: process.env.NODE_ENV === "test" } as any, audit: {} as any, payloads: {}, occurredAt: new Date() }, session); }
  async createAndStart(input: Creation) { const session = await mongoose.startSession(); let result: IInternalTopUpFunding | null = null; try { await session.withTransaction(async () => { let funding = await internalTopUpFundingRepository.findByTopUpRequestId(input.topUpRequestId, session); if (!funding) { funding = await internalTopUpFundingRepository.createFunding({ ...input, fundingReference: generateFinancialReference("INTERNAL_TOP_UP_FUNDING") }, session); await this.event(funding, ProviderEventType.TOP_UP_FUNDING_CREATED, ProviderOperation.CREATE_TOP_UP_FUNDING, session); } else if (!internalTopUpFundingRepository.matches(funding, input)) throw new InternalTopUpFundingError("Provider funding identity conflicts with the existing record.", "INTERNAL_TOP_UP_FUNDING_IDENTITY_CONFLICT"); if (funding.status === InternalTopUpFundingStatus.CREATED) { const updated = await internalTopUpFundingRepository.markProcessing(funding.fundingReference, new Date(), session); if (!updated) throw new InternalTopUpFundingError("Provider funding state changed concurrently.", "INTERNAL_TOP_UP_FUNDING_INVALID_STATUS"); funding = updated; await this.event(funding, ProviderEventType.TOP_UP_FUNDING_PROCESSING_STARTED, ProviderOperation.PROCESS_TOP_UP_FUNDING, session); } result = funding; }); } finally { await session.endSession(); } if (!result) throw new InternalTopUpFundingError("Provider funding did not start.", "INTERNAL_TOP_UP_FUNDING_INTEGRITY_ERROR", 500); return result; }
  async simulate(reference: string, outcome: InternalTopUpFundingOutcome, code?: InternalTopUpFundingFailureCode, reason?: unknown) { const failure = this.normalize(outcome, code, reason); const session = await mongoose.startSession(); let result: IInternalTopUpFunding | null = null; try { await session.withTransaction(async () => { const funding = await internalTopUpFundingRepository.findByFundingReference(reference, session); if (!funding) throw new InternalTopUpFundingError("Provider funding was not found.", "INTERNAL_TOP_UP_FUNDING_NOT_FOUND", 404); if (funding.status === InternalTopUpFundingStatus.SUCCEEDED) { if (outcome === InternalTopUpFundingOutcome.SUCCESS) { result = funding; return; } throw new InternalTopUpFundingError("Provider outcome conflicts with the persisted result.", "INTERNAL_TOP_UP_FUNDING_OUTCOME_CONFLICT"); } if (funding.status === InternalTopUpFundingStatus.FAILED) { if (outcome === InternalTopUpFundingOutcome.SUCCESS) throw new InternalTopUpFundingError("Provider outcome conflicts with the persisted result.", "INTERNAL_TOP_UP_FUNDING_OUTCOME_CONFLICT"); if (funding.failureCode === failure.failureCode && (funding.failureReason ?? undefined) === failure.failureReason) { result = funding; return; } throw new InternalTopUpFundingError("Provider failure payload conflicts with the persisted result.", "INTERNAL_TOP_UP_FUNDING_FAILURE_PAYLOAD_CONFLICT"); } if (funding.status !== InternalTopUpFundingStatus.PROCESSING) throw new InternalTopUpFundingError("Provider funding is not processing.", "INTERNAL_TOP_UP_FUNDING_INVALID_STATUS"); const updated = outcome === InternalTopUpFundingOutcome.SUCCESS ? await internalTopUpFundingRepository.markSucceeded(reference, new Date(), session) : await internalTopUpFundingRepository.markFailed(reference, new Date(), failure.failureCode!, failure.failureReason, session); if (!updated) throw new InternalTopUpFundingError("Provider funding state changed concurrently.", "INTERNAL_TOP_UP_FUNDING_INVALID_STATUS"); await this.event(updated, outcome === InternalTopUpFundingOutcome.SUCCESS ? ProviderEventType.TOP_UP_FUNDING_SUCCEEDED : ProviderEventType.TOP_UP_FUNDING_FAILED, outcome === InternalTopUpFundingOutcome.SUCCESS ? ProviderOperation.SUCCEED_TOP_UP_FUNDING : ProviderOperation.FAIL_TOP_UP_FUNDING, session); result = updated; }); } finally { await session.endSession(); } if (!result) throw new InternalTopUpFundingError("Provider funding simulation did not complete.", "INTERNAL_TOP_UP_FUNDING_INTEGRITY_ERROR", 500); return result; }
}
export const internalTopUpFundingService = new InternalTopUpFundingService();
