export const BOOKING_WALLET_RESERVATION_ERROR_CODES = [
  "BOOKING_WALLET_RESERVATION_WALLET_NOT_FOUND",
  "BOOKING_WALLET_RESERVATION_WALLET_OWNERSHIP_CONFLICT",
  "BOOKING_WALLET_RESERVATION_CURRENCY_CONFLICT",
  "BOOKING_WALLET_RESERVATION_INVALID_AMOUNT",
  "BOOKING_WALLET_RESERVATION_NOT_FOUND",
  "BOOKING_WALLET_RESERVATION_INSUFFICIENT_AVAILABLE_BALANCE",
  "BOOKING_WALLET_RESERVATION_IDENTITY_CONFLICT",
  "BOOKING_WALLET_RESERVATION_TRANSACTION_CONFLICT",
  "BOOKING_WALLET_RESERVATION_LEDGER_CONFLICT",
  "BOOKING_WALLET_RESERVATION_PROJECTION_CONFLICT",
  "BOOKING_WALLET_RESERVATION_PAYMENT_CONFLICT",
  "BOOKING_WALLET_RESERVATION_BOOKING_CONFLICT",
  "BOOKING_WALLET_RESERVATION_INVALID_STATUS",
  "BOOKING_WALLET_RESERVATION_INTEGRITY_ERROR",
] as const;

export type BookingWalletReservationErrorCode =
  (typeof BOOKING_WALLET_RESERVATION_ERROR_CODES)[number];

const STATUS_BY_CODE: Record<BookingWalletReservationErrorCode, number> = {
  BOOKING_WALLET_RESERVATION_WALLET_NOT_FOUND: 404,
  BOOKING_WALLET_RESERVATION_NOT_FOUND: 404,
  BOOKING_WALLET_RESERVATION_INVALID_AMOUNT: 422,
  BOOKING_WALLET_RESERVATION_INTEGRITY_ERROR: 500,
  BOOKING_WALLET_RESERVATION_WALLET_OWNERSHIP_CONFLICT: 409,
  BOOKING_WALLET_RESERVATION_CURRENCY_CONFLICT: 409,
  BOOKING_WALLET_RESERVATION_INSUFFICIENT_AVAILABLE_BALANCE: 409,
  BOOKING_WALLET_RESERVATION_IDENTITY_CONFLICT: 409,
  BOOKING_WALLET_RESERVATION_TRANSACTION_CONFLICT: 409,
  BOOKING_WALLET_RESERVATION_LEDGER_CONFLICT: 409,
  BOOKING_WALLET_RESERVATION_PROJECTION_CONFLICT: 409,
  BOOKING_WALLET_RESERVATION_PAYMENT_CONFLICT: 409,
  BOOKING_WALLET_RESERVATION_BOOKING_CONFLICT: 409,
  BOOKING_WALLET_RESERVATION_INVALID_STATUS: 409,
};

export class BookingWalletReservationError extends Error {
  readonly statusCode: number;

  constructor(
    message: string,
    readonly code: BookingWalletReservationErrorCode,
    options?: { cause?: unknown },
  ) {
    super(message);
    if (options?.cause !== undefined) {
      (this as Error & { cause?: unknown }).cause = options.cause;
    }
    this.name = "BookingWalletReservationError";
    this.statusCode = STATUS_BY_CODE[code];
  }
}
