export type BookingCreatorSettlementErrorCode =
  | "BOOKING_CREATOR_SETTLEMENT_BOOKING_NOT_FOUND"
  | "BOOKING_CREATOR_SETTLEMENT_PAYMENT_NOT_FOUND"
  | "BOOKING_CREATOR_SETTLEMENT_RESERVATION_NOT_FOUND"
  | "BOOKING_CREATOR_SETTLEMENT_ALLOCATION_NOT_FOUND"
  | "BOOKING_CREATOR_SETTLEMENT_CREATOR_NOT_FOUND"
  | "BOOKING_CREATOR_SETTLEMENT_WALLET_NOT_FOUND"
  | "BOOKING_CREATOR_SETTLEMENT_INVALID_BOOKING_STATUS"
  | "BOOKING_CREATOR_SETTLEMENT_INVALID_PAYMENT_STATUS"
  | "BOOKING_CREATOR_SETTLEMENT_INVALID_RESERVATION_STATUS"
  | "BOOKING_CREATOR_SETTLEMENT_INVALID_ALLOCATION_STATUS"
  | "BOOKING_CREATOR_SETTLEMENT_IDENTITY_CONFLICT"
  | "BOOKING_CREATOR_SETTLEMENT_AMOUNT_CONFLICT"
  | "BOOKING_CREATOR_SETTLEMENT_COMMISSION_CONFLICT"
  | "BOOKING_CREATOR_SETTLEMENT_CURRENCY_CONFLICT"
  | "BOOKING_CREATOR_SETTLEMENT_WALLET_OWNERSHIP_CONFLICT"
  | "BOOKING_CREATOR_SETTLEMENT_FINANCIAL_LOCKED"
  | "BOOKING_CREATOR_SETTLEMENT_DISPUTE_OPEN"
  | "BOOKING_CREATOR_SETTLEMENT_LEDGER_CONFLICT"
  | "BOOKING_CREATOR_SETTLEMENT_PROJECTION_CONFLICT"
  | "BOOKING_CREATOR_SETTLEMENT_TRANSACTION_CONFLICT"
  | "BOOKING_CREATOR_SETTLEMENT_COMPLETION_CONFLICT"
  | "BOOKING_CREATOR_SETTLEMENT_INTEGRITY_ERROR";

const statusFor = (code: BookingCreatorSettlementErrorCode): number => {
  if ([
    "BOOKING_CREATOR_SETTLEMENT_BOOKING_NOT_FOUND",
    "BOOKING_CREATOR_SETTLEMENT_PAYMENT_NOT_FOUND",
    "BOOKING_CREATOR_SETTLEMENT_RESERVATION_NOT_FOUND",
    "BOOKING_CREATOR_SETTLEMENT_ALLOCATION_NOT_FOUND",
    "BOOKING_CREATOR_SETTLEMENT_CREATOR_NOT_FOUND",
    "BOOKING_CREATOR_SETTLEMENT_WALLET_NOT_FOUND",
  ].includes(code)) return 404;
  if (code === "BOOKING_CREATOR_SETTLEMENT_INTEGRITY_ERROR") return 500;
  return 409;
};

export class BookingCreatorSettlementError extends Error {
  readonly code: BookingCreatorSettlementErrorCode;
  readonly statusCode: number;
  readonly cause?: unknown;

  constructor(
    message: string,
    code: BookingCreatorSettlementErrorCode,
    options: { cause?: unknown } = {},
  ) {
    super(message);
    this.name = "BookingCreatorSettlementError";
    this.code = code;
    this.statusCode = statusFor(code);
    this.cause = options.cause;
  }
}
