export const BOOKING_WALLET_CAPTURE_ERROR_CODES = [
  "BOOKING_WALLET_CAPTURE_BOOKING_NOT_FOUND",
  "BOOKING_WALLET_CAPTURE_PAYMENT_NOT_FOUND",
  "BOOKING_WALLET_CAPTURE_RESERVATION_NOT_FOUND",
  "BOOKING_WALLET_CAPTURE_INVALID_BOOKING_STATUS",
  "BOOKING_WALLET_CAPTURE_INVALID_PAYMENT_STATUS",
  "BOOKING_WALLET_CAPTURE_INVALID_RESERVATION_STATUS",
  "BOOKING_WALLET_CAPTURE_PAYMENT_METHOD_CONFLICT",
  "BOOKING_WALLET_CAPTURE_IDENTITY_CONFLICT",
  "BOOKING_WALLET_CAPTURE_AMOUNT_CONFLICT",
  "BOOKING_WALLET_CAPTURE_CURRENCY_CONFLICT",
  "BOOKING_WALLET_CAPTURE_CAUSE_CONFLICT",
  "BOOKING_WALLET_CAPTURE_FINANCIAL_LOCKED",
  "BOOKING_WALLET_CAPTURE_DISPUTE_OPEN",
  "BOOKING_WALLET_CAPTURE_INSUFFICIENT_RESERVED_BALANCE",
  "BOOKING_WALLET_CAPTURE_LEDGER_CONFLICT",
  "BOOKING_WALLET_CAPTURE_PROJECTION_CONFLICT",
  "BOOKING_WALLET_CAPTURE_TRANSACTION_CONFLICT",
  "BOOKING_WALLET_CAPTURE_ALREADY_RELEASED",
  "BOOKING_WALLET_CAPTURE_COMPLETION_CONFLICT",
  "BOOKING_WALLET_CAPTURE_INTEGRITY_ERROR",
] as const;

export type BookingWalletCaptureErrorCode =
  (typeof BOOKING_WALLET_CAPTURE_ERROR_CODES)[number];

export class BookingWalletReservationCaptureError extends Error {
  readonly statusCode: number;

  constructor(
    message: string,
    readonly code: BookingWalletCaptureErrorCode,
    options?: { cause?: unknown },
  ) {
    super(message);
    this.name = "BookingWalletReservationCaptureError";
    this.statusCode = [
      "BOOKING_WALLET_CAPTURE_BOOKING_NOT_FOUND",
      "BOOKING_WALLET_CAPTURE_PAYMENT_NOT_FOUND",
      "BOOKING_WALLET_CAPTURE_RESERVATION_NOT_FOUND",
    ].includes(code)
      ? 404
      : code === "BOOKING_WALLET_CAPTURE_INTEGRITY_ERROR"
        ? 500
        : 409;
    if (options?.cause !== undefined) {
      (this as Error & { cause?: unknown }).cause = options.cause;
    }
  }
}
