import { FinancialError } from "./FinancialError";

export type CreatorWithdrawalFinalizationErrorCode =
  | "CREATOR_WITHDRAWAL_FINALIZATION_WITHDRAWAL_NOT_FOUND"
  | "CREATOR_WITHDRAWAL_FINALIZATION_PROVIDER_NOT_FOUND"
  | "CREATOR_WITHDRAWAL_FINALIZATION_INVALID_WITHDRAWAL_STATUS"
  | "CREATOR_WITHDRAWAL_FINALIZATION_INVALID_PROVIDER_STATUS"
  | "CREATOR_WITHDRAWAL_FINALIZATION_PROVIDER_IDENTITY_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_DESTINATION_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_WALLET_NOT_FOUND"
  | "CREATOR_WITHDRAWAL_FINALIZATION_WALLET_OWNERSHIP_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_AMOUNT_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_CURRENCY_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_INSUFFICIENT_RESERVED_BALANCE"
  | "CREATOR_WITHDRAWAL_FINALIZATION_RESERVATION_LEDGER_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_RESERVATION_PROJECTION_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_LEDGER_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_PROJECTION_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_TRANSACTION_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_OUTCOME_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_REPLAY_CONFLICT"
  | "CREATOR_WITHDRAWAL_FINALIZATION_INTEGRITY_ERROR";

export class CreatorWithdrawalFinalizationError extends FinancialError {
  readonly statusCode: number;

  constructor(
    message: string,
    code: CreatorWithdrawalFinalizationErrorCode,
    options?: { cause?: unknown },
  ) {
    super(message, code, options);
    this.name = "CreatorWithdrawalFinalizationError";
    this.statusCode = code.endsWith("_NOT_FOUND")
      ? 404
      : code === "CREATOR_WITHDRAWAL_FINALIZATION_INTEGRITY_ERROR"
        ? 500
        : 409;
  }
}
