import { FinancialError } from "./FinancialError";

export type CreatorWithdrawalOperationalErrorCode =
  | "CREATOR_WITHDRAWAL_OPERATIONAL_WITHDRAWAL_NOT_FOUND"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_RECONCILIATION_NOT_FOUND"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_ALREADY_RESOLVED"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_INVALID_STATUS"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_INVALID_ACTION"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_CLASSIFICATION_CHANGED"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_SNAPSHOT_CONFLICT"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_RETRY_LIMIT_EXCEEDED"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_RETRY_NOT_ALLOWED"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_REPAIR_NOT_ALLOWED"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_REPAIR_AMBIGUOUS"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_REPAIR_CONFLICT"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_PROVIDER_CONFLICT"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_LEDGER_CONFLICT"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_PROJECTION_CONFLICT"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_WALLET_CONFLICT"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_AUDIT_CONFLICT"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_TRANSACTION_CONFLICT"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_REPLAY_CONFLICT"
  | "CREATOR_WITHDRAWAL_OPERATIONAL_INTEGRITY_ERROR";

export class CreatorWithdrawalOperationalError extends FinancialError {
  readonly statusCode: number;

  constructor(
    message: string,
    code: CreatorWithdrawalOperationalErrorCode,
    cause?: unknown,
  ) {
    super(message, code, { cause });
    this.name = "CreatorWithdrawalOperationalError";
    this.statusCode = code.endsWith("_NOT_FOUND") ? 404
      : code.endsWith("_INTEGRITY_ERROR") ? 500 : 409;
  }
}
