import { FinancialError } from "./FinancialError";

export type WalletConversionRequestErrorCode =
  | "WALLET_CONVERSION_INVALID_IDEMPOTENCY_KEY"
  | "WALLET_CONVERSION_INVALID_SOURCE_CURRENCY"
  | "WALLET_CONVERSION_INVALID_TARGET_CURRENCY"
  | "WALLET_CONVERSION_IDENTICAL_CURRENCIES"
  | "WALLET_CONVERSION_UNSUPPORTED_PAIR"
  | "WALLET_CONVERSION_INVALID_AMOUNT"
  | "WALLET_CONVERSION_SOURCE_WALLET_NOT_FOUND"
  | "WALLET_CONVERSION_SOURCE_WALLET_OWNERSHIP_CONFLICT"
  | "WALLET_CONVERSION_SOURCE_WALLET_CURRENCY_CONFLICT"
  | "WALLET_CONVERSION_INSUFFICIENT_AVAILABLE_BALANCE"
  | "WALLET_CONVERSION_FX_SNAPSHOT_NOT_FOUND"
  | "WALLET_CONVERSION_FX_SNAPSHOT_EXPIRED"
  | "WALLET_CONVERSION_FX_SNAPSHOT_CONFLICT"
  | "WALLET_CONVERSION_TARGET_AMOUNT_ZERO"
  | "WALLET_CONVERSION_IDEMPOTENCY_CONFLICT"
  | "WALLET_CONVERSION_REQUEST_NOT_FOUND"
  | "WALLET_CONVERSION_INVALID_PAGINATION"
  | "WALLET_CONVERSION_INTEGRITY_ERROR"
  | "WALLET_CONVERSION_INVALID_DECISION"
  | "WALLET_CONVERSION_REJECTION_CODE_REQUIRED"
  | "WALLET_CONVERSION_REJECTION_DATA_NOT_ALLOWED"
  | "WALLET_CONVERSION_INVALID_REJECTION_REASON"
  | "WALLET_CONVERSION_DECISION_CONFLICT"
  | "WALLET_CONVERSION_INVALID_STATUS"
  | "WALLET_CONVERSION_SNAPSHOT_NOT_FOUND"
  | "WALLET_CONVERSION_SNAPSHOT_EXPIRED"
  | "WALLET_CONVERSION_SNAPSHOT_CONFLICT"
  | "WALLET_CONVERSION_SOURCE_WALLET_CONFLICT"
  | "WALLET_CONVERSION_TARGET_WALLET_CONFLICT";

export class WalletConversionRequestError extends FinancialError {
  public readonly statusCode: number;

  constructor(message: string, code: WalletConversionRequestErrorCode,
    statusCode = 409, cause?: unknown) {
    super(message, code, { cause });
    this.statusCode = statusCode;
  }
}
