import { FinancialError } from "./FinancialError";

export type WalletConversionOperationalErrorCode =
  | "WALLET_CONVERSION_OPERATIONAL_INVALID_INPUT"
  | "WALLET_CONVERSION_OPERATIONAL_REQUEST_NOT_FOUND"
  | "WALLET_CONVERSION_OPERATIONAL_RECONCILIATION_NOT_FOUND"
  | "WALLET_CONVERSION_OPERATIONAL_RETRY_NOT_ALLOWED"
  | "WALLET_CONVERSION_OPERATIONAL_REPAIR_NOT_ALLOWED"
  | "WALLET_CONVERSION_OPERATIONAL_CLASSIFICATION_CONFLICT"
  | "WALLET_CONVERSION_OPERATIONAL_SNAPSHOT_CONFLICT"
  | "WALLET_CONVERSION_OPERATIONAL_PROVIDER_CONFLICT"
  | "WALLET_CONVERSION_OPERATIONAL_LEDGER_CONFLICT"
  | "WALLET_CONVERSION_OPERATIONAL_PROJECTION_CONFLICT"
  | "WALLET_CONVERSION_OPERATIONAL_AUDIT_CONFLICT"
  | "WALLET_CONVERSION_OPERATIONAL_REPLAY_CONFLICT"
  | "WALLET_CONVERSION_OPERATIONAL_TRANSACTION_CONFLICT"
  | "WALLET_CONVERSION_OPERATIONAL_INTEGRITY_FAILURE";

export class WalletConversionOperationalError extends FinancialError {
  readonly statusCode: number;

  constructor(message: string, code: WalletConversionOperationalErrorCode,
    cause?: unknown) {
    super(message, code, { cause });
    this.name = "WalletConversionOperationalError";
    this.statusCode = code.endsWith("_NOT_FOUND") ? 404
      : code.endsWith("_INVALID_INPUT") ? 422 : 409;
  }
}
