import { FinancialError } from "./FinancialError";

export const WalletTopUpAccountingErrorCode = {
  NOT_FOUND: "WALLET_TOP_UP_ACCOUNTING_NOT_FOUND",
  INVALID_STATUS: "WALLET_TOP_UP_ACCOUNTING_INVALID_STATUS",
  INVALID_REQUEST_STATUS: "WALLET_TOP_UP_ACCOUNTING_INVALID_REQUEST_STATUS",
  PROVIDER_LINK_MISSING: "WALLET_TOP_UP_ACCOUNTING_PROVIDER_LINK_MISSING",
  PROVIDER_LINK_CONFLICT: "WALLET_TOP_UP_ACCOUNTING_PROVIDER_LINK_CONFLICT",
  PROVIDER_NOT_SUCCEEDED: "WALLET_TOP_UP_ACCOUNTING_PROVIDER_NOT_SUCCEEDED",
  WALLET_NOT_FOUND: "WALLET_TOP_UP_ACCOUNTING_WALLET_NOT_FOUND",
  WALLET_OWNERSHIP_CONFLICT: "WALLET_TOP_UP_ACCOUNTING_WALLET_OWNERSHIP_CONFLICT",
  CURRENCY_CONFLICT: "WALLET_TOP_UP_ACCOUNTING_CURRENCY_CONFLICT",
  AMOUNT_CONFLICT: "WALLET_TOP_UP_ACCOUNTING_AMOUNT_CONFLICT",
  LEDGER_NOT_FOUND: "WALLET_TOP_UP_ACCOUNTING_LEDGER_NOT_FOUND",
  LEDGER_IDENTITY_CONFLICT: "WALLET_TOP_UP_ACCOUNTING_LEDGER_IDENTITY_CONFLICT",
  PROJECTION_NOT_FOUND: "WALLET_TOP_UP_ACCOUNTING_PROJECTION_NOT_FOUND",
  PROJECTION_IDENTITY_CONFLICT: "WALLET_TOP_UP_ACCOUNTING_PROJECTION_IDENTITY_CONFLICT",
  LINK_MISSING: "WALLET_TOP_UP_ACCOUNTING_LINK_MISSING",
  TRANSACTION_CONFLICT: "WALLET_TOP_UP_ACCOUNTING_TRANSACTION_CONFLICT",
  INTEGRITY_ERROR: "WALLET_TOP_UP_ACCOUNTING_INTEGRITY_ERROR",
  COMPLETION_CONFLICT: "WALLET_TOP_UP_ACCOUNTING_COMPLETION_CONFLICT",
} as const;

export type WalletTopUpAccountingErrorCode =
  (typeof WalletTopUpAccountingErrorCode)[keyof typeof WalletTopUpAccountingErrorCode];

export class WalletTopUpAccountingError extends FinancialError {
  public readonly statusCode: number;

  constructor(
    message: string,
    code: WalletTopUpAccountingErrorCode,
    statusCode = 409,
  ) {
    super(message, code);
    this.name = this.constructor.name;
    this.statusCode = statusCode;
  }
}
