export const PROFILE_VERIFICATION_INFERENCE_PIPELINE_KINDS = ["TEST_SYNTHETIC", "MODEL_RUNTIME", "MODEL_RUNTIME_DETECTOR_ONLY"] as const;
export type ProfileVerificationInferencePipelineKind = (typeof PROFILE_VERIFICATION_INFERENCE_PIPELINE_KINDS)[number];

export const PROFILE_VERIFICATION_SHADOW_IDENTITY_STATUSES = ["PENDING", "PROCESSING", "COMPLETED", "FAILED"] as const;
export type ProfileVerificationShadowIdentityStatus = (typeof PROFILE_VERIFICATION_SHADOW_IDENTITY_STATUSES)[number];
export const PROFILE_VERIFICATION_SHADOW_IDENTITY_CONCLUSIONS = ["LIKELY_MATCH", "LIKELY_MISMATCH", "UNABLE_TO_DETERMINE"] as const;
export type ProfileVerificationShadowIdentityConclusion = (typeof PROFILE_VERIFICATION_SHADOW_IDENTITY_CONCLUSIONS)[number];

export const PROFILE_VERIFICATION_FACE_COUNT_FINDINGS = ["NOT_RUN", "ZERO", "ONE", "MULTIPLE", "UNCERTAIN"] as const;
export type ProfileVerificationFaceCountFinding = (typeof PROFILE_VERIFICATION_FACE_COUNT_FINDINGS)[number];

export const PROFILE_VERIFICATION_CAPTURE_USABILITY_FINDINGS = ["NOT_RUN", "USABLE", "UNUSABLE", "UNCERTAIN"] as const;
export type ProfileVerificationCaptureUsabilityFinding = (typeof PROFILE_VERIFICATION_CAPTURE_USABILITY_FINDINGS)[number];

export const PROFILE_VERIFICATION_CAPTURE_REASON_CODES = [
  "FACE_TOO_SMALL", "FACE_TOO_LARGE", "POOR_ALIGNMENT", "LOW_IMAGE_QUALITY", "OCCLUDED", "DETECTION_UNCERTAIN", "CORRUPT_INPUT",
] as const;
export type ProfileVerificationCaptureReasonCode = (typeof PROFILE_VERIFICATION_CAPTURE_REASON_CODES)[number];

export const PROFILE_VERIFICATION_CROSS_CAPTURE_FINDINGS = ["NOT_RUN", "CONSISTENT", "INCONSISTENT", "UNCERTAIN"] as const;
export type ProfileVerificationCrossCaptureFinding = (typeof PROFILE_VERIFICATION_CROSS_CAPTURE_FINDINGS)[number];

export const PROFILE_VERIFICATION_AVATAR_FINDINGS = ["NOT_RUN", "NO_USABLE_FACE", "MULTIPLE_FACES", "MATCH_SUPPORTED", "MATCH_UNCERTAIN", "MATCH_NOT_SUPPORTED"] as const;
export type ProfileVerificationAvatarFinding = (typeof PROFILE_VERIFICATION_AVATAR_FINDINGS)[number];

export const PROFILE_VERIFICATION_ANTI_SPOOF_FINDINGS = ["NOT_RUN"] as const;
export type ProfileVerificationAntiSpoofFinding = (typeof PROFILE_VERIFICATION_ANTI_SPOOF_FINDINGS)[number];

export const PROFILE_VERIFICATION_INFERENCE_ERROR_CODES = [
  "INVALID_INPUT", "STALE_SUBMISSION", "TERMINAL_REQUEST", "BIOMETRIC_RETENTION_EXPIRED", "SESSION_NOT_COMPLETE", "EVIDENCE_INCOMPLETE", "EVIDENCE_NOT_AVAILABLE", "EVIDENCE_INTEGRITY_FAILED", "EVIDENCE_TOO_LARGE", "EVIDENCE_UNSUPPORTED_TYPE", "EVIDENCE_RETRIEVAL_TIMEOUT", "EVIDENCE_RETRIEVAL_FAILED", "PIPELINE_IDENTITY_INVALID", "FINDINGS_INVALID", "TECHNICAL_FAILURE",
] as const;
export type ProfileVerificationInferenceErrorCode = (typeof PROFILE_VERIFICATION_INFERENCE_ERROR_CODES)[number];
