// backend/src/constants/internalProvider/providerEventType.enum.ts

/**
 * ------------------------------------------------------------------
 * STHN Internal Provider Platform
 * Provider Event Type
 * ------------------------------------------------------------------
 *
 * Represents immutable events emitted by the Internal Provider.
 *
 * Every provider action generates one or more events which are stored
 * in InternalProviderEvent for auditing, replay, reconciliation,
 * debugging and timeline reconstruction.
 *
 * Provider events are append-only and MUST NEVER be modified.
 * ------------------------------------------------------------------
 */

export enum ProviderEventType {
  CONVERSION_PROVIDER_CREATED = "CONVERSION_PROVIDER_CREATED",
  CONVERSION_PROVIDER_INITIALIZED = "CONVERSION_PROVIDER_INITIALIZED",
  CONVERSION_PROVIDER_PROCESSING = "CONVERSION_PROVIDER_PROCESSING",
  CONVERSION_PROVIDER_SUCCEEDED = "CONVERSION_PROVIDER_SUCCEEDED",
  CONVERSION_PROVIDER_FAILED = "CONVERSION_PROVIDER_FAILED",
  WITHDRAWAL_PROVIDER_CREATED = "WITHDRAWAL_PROVIDER_CREATED",
  WITHDRAWAL_PROVIDER_INITIALIZED = "WITHDRAWAL_PROVIDER_INITIALIZED",
  WITHDRAWAL_PROVIDER_PROCESSING = "WITHDRAWAL_PROVIDER_PROCESSING",
  WITHDRAWAL_PROVIDER_SUCCEEDED = "WITHDRAWAL_PROVIDER_SUCCEEDED",
  WITHDRAWAL_PROVIDER_FAILED = "WITHDRAWAL_PROVIDER_FAILED",
  TOP_UP_FUNDING_CREATED = "TOP_UP_FUNDING_CREATED",
  TOP_UP_FUNDING_PROCESSING_STARTED = "TOP_UP_FUNDING_PROCESSING_STARTED",
  TOP_UP_FUNDING_SUCCEEDED = "TOP_UP_FUNDING_SUCCEEDED",
  TOP_UP_FUNDING_FAILED = "TOP_UP_FUNDING_FAILED",
  /**
   * Payment Events
   */
  PAYMENT_CREATED = "PAYMENT_CREATED",
  PAYMENT_AUTHORIZED = "PAYMENT_AUTHORIZED",
  PAYMENT_CAPTURED = "PAYMENT_CAPTURED",
  PAYMENT_PARTIALLY_CAPTURED = "PAYMENT_PARTIALLY_CAPTURED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_CANCELLED = "PAYMENT_CANCELLED",
  PAYMENT_EXPIRED = "PAYMENT_EXPIRED",

  /**
   * Refund Events
   */
  REFUND_CREATED = "REFUND_CREATED",

  REFUND_PROCESSING = "REFUND_PROCESSING",

  REFUND_COMPLETED = "REFUND_COMPLETED",

  REFUND_PARTIALLY_COMPLETED = "REFUND_PARTIALLY_COMPLETED",

  REFUND_FAILED = "REFUND_FAILED",

  REFUND_CANCELLED = "REFUND_CANCELLED",

  REFUND_EXPIRED = "REFUND_EXPIRED",

  /**
   * Settlement Events
   */
  SETTLEMENT_CREATED = "SETTLEMENT_CREATED",

  SETTLEMENT_SCHEDULED = "SETTLEMENT_SCHEDULED",

  SETTLEMENT_PROCESSING = "SETTLEMENT_PROCESSING",

  SETTLEMENT_PARTIALLY_COMPLETED = "SETTLEMENT_PARTIALLY_COMPLETED",

  SETTLEMENT_COMPLETED = "SETTLEMENT_COMPLETED",

  SETTLEMENT_FAILED = "SETTLEMENT_FAILED",

  SETTLEMENT_CANCELLED = "SETTLEMENT_CANCELLED",

  SETTLEMENT_EXPIRED = "SETTLEMENT_EXPIRED",
  /**
   * Payout Events
   */
  PAYOUT_CREATED = "PAYOUT_CREATED",

  PAYOUT_SCHEDULED = "PAYOUT_SCHEDULED",

  PAYOUT_INITIATED = "PAYOUT_INITIATED",

  PAYOUT_PROCESSING = "PAYOUT_PROCESSING",

  PAYOUT_COMPLETED = "PAYOUT_COMPLETED",

  PAYOUT_PARTIALLY_COMPLETED = "PAYOUT_PARTIALLY_COMPLETED",

  PAYOUT_FAILED = "PAYOUT_FAILED",

  PAYOUT_CANCELLED = "PAYOUT_CANCELLED",

  PAYOUT_EXPIRED = "PAYOUT_EXPIRED",

  PAYOUT_REVERSED = "PAYOUT_REVERSED",

  /**
   * Webhook Events
   */
  WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED",

  WEBHOOK_VALIDATING = "WEBHOOK_VALIDATING",

  WEBHOOK_VERIFIED = "WEBHOOK_VERIFIED",

  WEBHOOK_PROCESSING = "WEBHOOK_PROCESSING",

  WEBHOOK_PROCESSED = "WEBHOOK_PROCESSED",

  WEBHOOK_RETRIED = "WEBHOOK_RETRIED",

  WEBHOOK_REPLAYED = "WEBHOOK_REPLAYED",

  WEBHOOK_FAILED = "WEBHOOK_FAILED",

  WEBHOOK_REJECTED = "WEBHOOK_REJECTED",

  WEBHOOK_EXPIRED = "WEBHOOK_EXPIRED",

  /**
   * Provider Events
   */
  PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT",
  PROVIDER_NETWORK_ERROR = "PROVIDER_NETWORK_ERROR",
  PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED",
  PROVIDER_RETRY_SCHEDULED = "PROVIDER_RETRY_SCHEDULED",

  /**
   * Administrative Events
   */
  ADMIN_OVERRIDE = "ADMIN_OVERRIDE",
  ADMIN_SIMULATION = "ADMIN_SIMULATION",
  ADMIN_RESET = "ADMIN_RESET",

  /**
   * FX Events (Future Phase)
   */
  FX_RATE_IMPORTED = "FX_RATE_IMPORTED",
  FX_RATE_OVERRIDDEN = "FX_RATE_OVERRIDDEN",
  FX_CONVERSION_PERFORMED = "FX_CONVERSION_PERFORMED",

  /**
   * Reconciliation Events (Future Phase)
   */
  RECONCILIATION_STARTED = "RECONCILIATION_STARTED",
  RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED",
  RECONCILIATION_FAILED = "RECONCILIATION_FAILED",
}

export default ProviderEventType;
