// backend/src/constants/internalProvider/providerOperation.enum.ts

/**
 * ------------------------------------------------------------------
 * STHN Internal Provider Platform
 * Provider Operation
 * ------------------------------------------------------------------
 *
 * Represents executable operations supported by a payment provider.
 *
 * These operations are used by:
 * - Internal Provider
 * - Admin Simulator
 * - Future Payment Providers
 * - Retry Engine
 * - Job Scheduler
 * - Reconciliation Engine
 *
 * NOTE:
 * This enum represents ACTIONS, not EVENTS or STATUSES.
 * ------------------------------------------------------------------
 */

export enum ProviderOperation {
  CREATE_CONVERSION_PROVIDER_REQUEST = "CREATE_CONVERSION_PROVIDER_REQUEST",
  INITIALIZE_CONVERSION_PROVIDER_REQUEST =
    "INITIALIZE_CONVERSION_PROVIDER_REQUEST",
  PROCESS_CONVERSION_PROVIDER_REQUEST =
    "PROCESS_CONVERSION_PROVIDER_REQUEST",
  SUCCEED_CONVERSION_PROVIDER_REQUEST =
    "SUCCEED_CONVERSION_PROVIDER_REQUEST",
  FAIL_CONVERSION_PROVIDER_REQUEST = "FAIL_CONVERSION_PROVIDER_REQUEST",
  CREATE_WITHDRAWAL_PROVIDER_REQUEST = "CREATE_WITHDRAWAL_PROVIDER_REQUEST",
  INITIALIZE_WITHDRAWAL_PROVIDER_REQUEST =
    "INITIALIZE_WITHDRAWAL_PROVIDER_REQUEST",
  PROCESS_WITHDRAWAL_PROVIDER_REQUEST =
    "PROCESS_WITHDRAWAL_PROVIDER_REQUEST",
  SUCCEED_WITHDRAWAL_PROVIDER_REQUEST =
    "SUCCEED_WITHDRAWAL_PROVIDER_REQUEST",
  FAIL_WITHDRAWAL_PROVIDER_REQUEST = "FAIL_WITHDRAWAL_PROVIDER_REQUEST",
  CREATE_TOP_UP_FUNDING = "CREATE_TOP_UP_FUNDING",
  PROCESS_TOP_UP_FUNDING = "PROCESS_TOP_UP_FUNDING",
  SUCCEED_TOP_UP_FUNDING = "SUCCEED_TOP_UP_FUNDING",
  FAIL_TOP_UP_FUNDING = "FAIL_TOP_UP_FUNDING",
  /**
   * Payment Operations
   */
  CREATE_PAYMENT = "CREATE_PAYMENT",
  AUTHORIZE_PAYMENT = "AUTHORIZE_PAYMENT",
  CAPTURE_PAYMENT = "CAPTURE_PAYMENT",
  PARTIAL_CAPTURE_PAYMENT = "PARTIAL_CAPTURE_PAYMENT",
  CANCEL_PAYMENT = "CANCEL_PAYMENT",
  EXPIRE_PAYMENT = "EXPIRE_PAYMENT",
  FAIL_PAYMENT = "FAIL_PAYMENT",

  /**
   * Refund Operations
   */
  CREATE_REFUND = "CREATE_REFUND",

  PROCESS_REFUND = "PROCESS_REFUND",

  PARTIAL_REFUND = "PARTIAL_REFUND",

  COMPLETE_REFUND = "COMPLETE_REFUND",

  FAIL_REFUND = "FAIL_REFUND",

  CANCEL_REFUND = "CANCEL_REFUND",

  EXPIRE_REFUND = "EXPIRE_REFUND",

  /**
   * Settlement Operations
   */
  CREATE_SETTLEMENT = "CREATE_SETTLEMENT",

  SCHEDULE_SETTLEMENT = "SCHEDULE_SETTLEMENT",

  PROCESS_SETTLEMENT = "PROCESS_SETTLEMENT",

  PARTIAL_SETTLEMENT = "PARTIAL_SETTLEMENT",

  COMPLETE_SETTLEMENT = "COMPLETE_SETTLEMENT",

  FAIL_SETTLEMENT = "FAIL_SETTLEMENT",

  CANCEL_SETTLEMENT = "CANCEL_SETTLEMENT",

  EXPIRE_SETTLEMENT = "EXPIRE_SETTLEMENT",

  /**
   * Payout Operations
   */
  CREATE_PAYOUT = "CREATE_PAYOUT",

  SCHEDULE_PAYOUT = "SCHEDULE_PAYOUT",

  PROCESS_PAYOUT = "PROCESS_PAYOUT",

  INITIATE_PAYOUT = "INITIATE_PAYOUT",

  PARTIAL_PAYOUT = "PARTIAL_PAYOUT",

  COMPLETE_PAYOUT = "COMPLETE_PAYOUT",

  FAIL_PAYOUT = "FAIL_PAYOUT",

  CANCEL_PAYOUT = "CANCEL_PAYOUT",

  EXPIRE_PAYOUT = "EXPIRE_PAYOUT",

  REVERSE_PAYOUT = "REVERSE_PAYOUT",

  /**
   * Webhook Operations
   */
  RECEIVE_WEBHOOK = "RECEIVE_WEBHOOK",

  VALIDATE_WEBHOOK = "VALIDATE_WEBHOOK",

  VERIFY_WEBHOOK = "VERIFY_WEBHOOK",

  PROCESS_WEBHOOK = "PROCESS_WEBHOOK",

  RETRY_WEBHOOK = "RETRY_WEBHOOK",

  REPLAY_WEBHOOK = "REPLAY_WEBHOOK",

  FAIL_WEBHOOK = "FAIL_WEBHOOK",

  REJECT_WEBHOOK = "REJECT_WEBHOOK",

  EXPIRE_WEBHOOK = "EXPIRE_WEBHOOK",

  /**
   * Retry Operations
   */
  RETRY_OPERATION = "RETRY_OPERATION",

  /**
   * FX Operations (Future Phase)
   */
  IMPORT_EXCHANGE_RATES = "IMPORT_EXCHANGE_RATES",
  OVERRIDE_EXCHANGE_RATE = "OVERRIDE_EXCHANGE_RATE",
  CONVERT_CURRENCY = "CONVERT_CURRENCY",

  /**
   * Reconciliation Operations (Future Phase)
   */
  START_RECONCILIATION = "START_RECONCILIATION",
  VERIFY_RECONCILIATION = "VERIFY_RECONCILIATION",

  /**
   * Administrative Operations
   */
  MANUAL_STATUS_CHANGE = "MANUAL_STATUS_CHANGE",
  RESET_PROVIDER_DATA = "RESET_PROVIDER_DATA",
}

export default ProviderOperation;
