import { ClientSession, Types } from "mongoose";
import { IInternalTopUpFunding, InternalTopUpFunding } from "../models/internalTopUpFunding.model";
import { InternalTopUpFundingStatus } from "../enums/financial/internalTopUpFundingStatus.enum";
import { InternalTopUpFundingFailureCode } from "../enums/financial/internalTopUpFundingFailureCode.enum";
import { InternalTopUpFundingError } from "../errors/financial/InternalTopUpFundingError";
export class InternalTopUpFundingRepository {
  async createFunding(data: Pick<IInternalTopUpFunding, "fundingReference" | "topUpRequestId" | "topUpReference" | "amount" | "currency" | "idempotencyKey" | "requestFingerprint">, session?: ClientSession) { try { const [created] = await InternalTopUpFunding.create([{ ...data, status: InternalTopUpFundingStatus.CREATED }], { session }); return created; } catch (error: any) { if (error?.code !== 11000) throw error; const existing = await this.findByTopUpRequestId(data.topUpRequestId, session); if (!existing) throw new InternalTopUpFundingError("Provider funding identity could not be recovered.", "INTERNAL_TOP_UP_FUNDING_INTEGRITY_ERROR", 500, { cause: error }); if (!this.matches(existing, data)) throw new InternalTopUpFundingError("Provider funding identity conflicts with the existing record.", "INTERNAL_TOP_UP_FUNDING_DUPLICATE_IDENTITY_CONFLICT"); return existing; } }
  matches(existing: IInternalTopUpFunding, data: Pick<IInternalTopUpFunding, "topUpRequestId" | "topUpReference" | "amount" | "currency" | "idempotencyKey" | "requestFingerprint">) { return existing.topUpRequestId.equals(data.topUpRequestId) && existing.topUpReference === data.topUpReference && existing.amount === data.amount && existing.currency === data.currency && existing.idempotencyKey === data.idempotencyKey && existing.requestFingerprint === data.requestFingerprint; }
  findByTopUpRequestId(topUpRequestId: Types.ObjectId, session?: ClientSession) { return InternalTopUpFunding.findOne({ topUpRequestId }).select("+requestFingerprint").session(session ?? null).exec(); }
  findByFundingReference(fundingReference: string, session?: ClientSession) { return InternalTopUpFunding.findOne({ fundingReference }).select("+requestFingerprint").session(session ?? null).exec(); }
  markProcessing(fundingReference: string, processingStartedAt: Date, session?: ClientSession) { return InternalTopUpFunding.findOneAndUpdate({ fundingReference, status: InternalTopUpFundingStatus.CREATED }, { $set: { status: InternalTopUpFundingStatus.PROCESSING, processingStartedAt } }, { new: true, session }).exec(); }
  markSucceeded(fundingReference: string, succeededAt: Date, session?: ClientSession) { return InternalTopUpFunding.findOneAndUpdate({ fundingReference, status: InternalTopUpFundingStatus.PROCESSING }, { $set: { status: InternalTopUpFundingStatus.SUCCEEDED, succeededAt } }, { new: true, session }).exec(); }
  markFailed(fundingReference: string, failedAt: Date, failureCode: InternalTopUpFundingFailureCode, failureReason: string | undefined, session?: ClientSession) { return InternalTopUpFunding.findOneAndUpdate({ fundingReference, status: InternalTopUpFundingStatus.PROCESSING }, { $set: { status: InternalTopUpFundingStatus.FAILED, failedAt, failureCode, ...(failureReason ? { failureReason } : {}) } }, { new: true, session }).exec(); }
}
export const internalTopUpFundingRepository = new InternalTopUpFundingRepository();
