import { ClientSession, Types } from "mongoose";
import { IWalletTopUpRequest, WalletTopUpRequest } from "../models/walletTopUpRequest.model";
import { WalletTopUpRequestStatus } from "../enums/financial/walletTopUpRequestStatus.enum";
import { WalletTopUpRejectionCode } from "../enums/financial/walletTopUpRejectionCode.enum";
export class WalletTopUpRequestRepository {
  findByReferenceForAccounting(topUpReference: string) { return WalletTopUpRequest.findOne({ topUpReference }).select("+providerFundingId +ledgerEntryId +walletProjectionOperationId").select("+failureFinalizedBy").exec(); }
  findByUserAndIdempotencyKey(userId: Types.ObjectId, idempotencyKey: string) { return WalletTopUpRequest.findOne({ userId, idempotencyKey }).select("+requestFingerprint").exec(); }
  findByUserAndReference(userId: Types.ObjectId, topUpReference: string) { return WalletTopUpRequest.findOne({ userId, topUpReference }).exec(); } findByReference(topUpReference: string) { return WalletTopUpRequest.findOne({ topUpReference }).exec(); }
  createPending(data: Pick<IWalletTopUpRequest, "topUpReference" | "userId" | "walletId" | "amount" | "currency" | "idempotencyKey" | "requestFingerprint" | "requestedAt">) { return WalletTopUpRequest.create({ ...data, status: WalletTopUpRequestStatus.PENDING }); }
  approvePending(input: { topUpReference: string; decidedBy: Types.ObjectId; decidedAt: Date }) { return WalletTopUpRequest.findOneAndUpdate({ topUpReference: input.topUpReference, status: WalletTopUpRequestStatus.PENDING }, { $set: { status: WalletTopUpRequestStatus.APPROVED, decidedBy: input.decidedBy, decidedAt: input.decidedAt }, $unset: { rejectionCode: 1, rejectionReason: 1 } }, { new: true, runValidators: true }).exec(); }
  rejectPending(input: { topUpReference: string; decidedBy: Types.ObjectId; decidedAt: Date; rejectionCode: WalletTopUpRejectionCode; rejectionReason?: string }) { return WalletTopUpRequest.findOneAndUpdate({ topUpReference: input.topUpReference, status: WalletTopUpRequestStatus.PENDING }, { $set: { status: WalletTopUpRequestStatus.REJECTED, decidedBy: input.decidedBy, decidedAt: input.decidedAt, rejectionCode: input.rejectionCode, ...(input.rejectionReason ? { rejectionReason: input.rejectionReason } : {}) }, $unset: input.rejectionReason ? {} : { rejectionReason: 1 } }, { new: true, runValidators: true }).exec(); }
  startProcessingApproved(input: { topUpReference: string; providerFundingId: Types.ObjectId; providerFundingReference: string; processingStartedAt: Date; session?: ClientSession }) { return WalletTopUpRequest.findOneAndUpdate({ topUpReference: input.topUpReference, status: WalletTopUpRequestStatus.APPROVED }, { $set: { status: WalletTopUpRequestStatus.PROCESSING, providerFundingId: input.providerFundingId, providerFundingReference: input.providerFundingReference, processingStartedAt: input.processingStartedAt } }, { new: true, session: input.session, runValidators: true }).exec(); }
  completeProcessingWithAccounting(input: { topUpReference: string; providerFundingReference: string; ledgerEntryId: Types.ObjectId; ledgerReference: string; walletProjectionOperationId: Types.ObjectId; walletProjectionOperationReference: string; accountingTransactionId: string; completedAt: Date; session?: ClientSession }) { return WalletTopUpRequest.findOneAndUpdate({ topUpReference: input.topUpReference, status: WalletTopUpRequestStatus.PROCESSING, providerFundingReference: input.providerFundingReference }, { $set: { status: WalletTopUpRequestStatus.COMPLETED, ledgerEntryId: input.ledgerEntryId, ledgerReference: input.ledgerReference, walletProjectionOperationId: input.walletProjectionOperationId, walletProjectionOperationReference: input.walletProjectionOperationReference, accountingTransactionId: input.accountingTransactionId, accountingCompletedAt: input.completedAt, completedAt: input.completedAt } }, { new: true, session: input.session, runValidators: true }).exec(); }
  finalizeProcessingAsFailed(input: { topUpReference: string; providerFundingId: Types.ObjectId; providerFundingReference: string; failureCode: string; failureReason?: string; providerFailedAt: Date; failureFinalizedAt: Date; failureFinalizedBy: Types.ObjectId }) { return WalletTopUpRequest.findOneAndUpdate({ topUpReference: input.topUpReference, status: WalletTopUpRequestStatus.PROCESSING, providerFundingId: input.providerFundingId, providerFundingReference: input.providerFundingReference }, { $set: { status: WalletTopUpRequestStatus.FAILED, failureCode: input.failureCode, ...(input.failureReason ? { failureReason: input.failureReason } : {}), providerFailedAt: input.providerFailedAt, failureFinalizedAt: input.failureFinalizedAt, failureFinalizedBy: input.failureFinalizedBy } }, { new: true, runValidators: true }).select("+providerFundingId +ledgerEntryId +walletProjectionOperationId +failureFinalizedBy").exec(); }
  repairMissingAccountingLinks(input: { topUpReference: string; expectedStatus: WalletTopUpRequestStatus; providerFundingId: Types.ObjectId; providerFundingReference: string; fields: { ledgerEntryId?: Types.ObjectId; ledgerReference?: string; walletProjectionOperationId?: Types.ObjectId; walletProjectionOperationReference?: string; accountingTransactionId?: string } }) { const set: Record<string, unknown> = {}; const missing: Record<string, unknown>[] = []; for (const [field, value] of Object.entries(input.fields)) { if (value === undefined) continue; set[field] = value; missing.push({ $or: [{ [field]: { $exists: false } }, { [field]: null }] }); } return WalletTopUpRequest.findOneAndUpdate({ topUpReference: input.topUpReference, status: input.expectedStatus, providerFundingId: input.providerFundingId, providerFundingReference: input.providerFundingReference, ...(missing.length ? { $and: missing } : {}) }, { $set: set }, { new: true, runValidators: true }).select("+providerFundingId +ledgerEntryId +walletProjectionOperationId +failureFinalizedBy").exec(); }
  listByUser(userId: Types.ObjectId, page: number, limit: number) { return WalletTopUpRequest.find({ userId }).sort({ requestedAt: -1, _id: -1 }).skip((page - 1) * limit).limit(limit).exec(); } listPending(page: number, limit: number) { return WalletTopUpRequest.find({ status: WalletTopUpRequestStatus.PENDING }).sort({ requestedAt: 1, _id: 1 }).skip((page - 1) * limit).limit(limit).exec(); }
}
export const walletTopUpRequestRepository = new WalletTopUpRequestRepository();
