import assert from "node:assert/strict";
import crypto from "node:crypto";
import { after, before, beforeEach, test } from "node:test";
import { Types } from "mongoose";
import User from "../../models/User";
import { UserProfile } from "../../models/userProfile.model";
import { ProfileVerificationInferenceResult } from "../../models/profileVerificationInferenceResult.model";
import { ProfileVerificationRequest } from "../../models/profileVerificationRequest.model";
import { ensureActiveProfileVerificationRequest } from "../../services/profile/profileVerificationRequest.service";
import { applyProfileVerificationAiDecision } from "../../services/profile/profileVerificationAiDecision.service";
import { clearPhase7HDatabase, connectPhase7HDatabase, disconnectPhase7HDatabase } from "../financial/phase7h/helpers/database";

const hash = (value: string) => crypto.createHash("sha256").update(value).digest("hex");
const setup = async (suffix: string, gated = false) => {
  const previousPolicy = process.env.STHN_PROFILE_VERIFICATION_POLICY;
  if (gated) process.env.STHN_PROFILE_VERIFICATION_POLICY = "GATED_MULTI_MEDIA_V1";
  else delete process.env.STHN_PROFILE_VERIFICATION_POLICY;
  const user = await User.create({ email: `ai-decision-${suffix}@test.local`, password: "test-password", status: "active", governanceState: "ACTIVE" });
  const profile = await UserProfile.create({ userId: user._id, username: `ai-decision-${suffix}`, dateOfBirth: new Date("1990-01-01"), interests: [], bio: "Test.", avatar: "https://example.test/avatar.jpg", cover: "https://example.test/cover.jpg", profilePhotos: gated ? Array.from({ length: 6 }, (_, index) => `https://example.test/photo-${index}.jpg`) : ["https://example.test/photo-a.jpg", "https://example.test/photo-b.jpg"], profileStatus: "pending_verification", verificationSubmittedAt: new Date(), verificationSubmissionVersion: 1 });
  const request = (await ensureActiveProfileVerificationRequest(profile)).request;
  if (previousPolicy === undefined) delete process.env.STHN_PROFILE_VERIFICATION_POLICY; else process.env.STHN_PROFILE_VERIFICATION_POLICY = previousPolicy;
  return { profile, request };
};
const result = async (request: Awaited<ReturnType<typeof setup>>["request"], input: { similarity?: number; threshold?: number; conclusion: "LIKELY_MATCH" | "LIKELY_MISMATCH" | "UNABLE_TO_DETERMINE"; mismatch?: boolean }) => ProfileVerificationInferenceResult.create({
  inferenceReference: `PROFILE_INFERENCE_AI_${new Types.ObjectId()}`, inferenceRunFingerprint: hash(String(new Types.ObjectId())), verificationRequestId: input.mismatch ? new Types.ObjectId() : request._id, profileId: request.profileId, userId: request.userId, profileSubmissionVersion: request.profileSubmissionVersion, faceVerificationSessionId: new Types.ObjectId(), evidenceSetFingerprint: hash(`e-${new Types.ObjectId()}`), pipelineManifestFingerprint: hash(`p-${new Types.ObjectId()}`), pipeline: { kind: "MODEL_RUNTIME", pipelineVersion: "test", runtimeIdentifier: "test", runtimeVersion: "1" }, findings: { captures: [0, 1, 2, 3, 4].map((challengeIndex) => ({ challengeIndex, challenge: "NEUTRAL", faceCount: "ONE", usability: "USABLE", reasonCodes: [] })), crossCapture: { status: "NOT_RUN", usableCaptureCount: 5, outlierCaptureCount: 0 }, avatar: { status: "MATCH_UNCERTAIN" }, antiSpoof: { status: "NOT_RUN" } }, shadowIdentityAnalysis: { status: "COMPLETED", conclusion: input.conclusion, ...(input.similarity === undefined ? {} : { similarity: input.similarity }), ...(input.threshold === undefined ? {} : { threshold: input.threshold }), model: { identifier: "OPENCV_ZOO_SFACE", version: "face_recognition_sface_2021dec" }, processedAt: new Date(), ...(input.conclusion === "UNABLE_TO_DETERMINE" ? { reasonCode: "THRESHOLD_NOT_CONFIGURED", reason: "Threshold is not configured." } : {}) }, retentionDeadline: new Date(Date.now() + 86_400_000),
});

before(async () => connectPhase7HDatabase(), { timeout: 120_000 }); beforeEach(async () => clearPhase7HDatabase()); after(async () => disconnectPhase7HDatabase(), { timeout: 30_000 });
test("above and equal threshold positive results approve through the canonical lifecycle and persist the AI snapshot", async () => {
  for (const [suffix, similarity] of [["above", 0.95], ["equal", 0.9]] as const) { const { profile, request } = await setup(suffix); const inference = await result(request, { similarity, threshold: 0.9, conclusion: "LIKELY_MATCH" }); await applyProfileVerificationAiDecision({ request, result: inference }); const stored = await ProfileVerificationRequest.findById(request._id); assert.equal(stored?.status, "APPROVED"); assert.equal(stored?.decisionAuthority, "AI"); assert.deepEqual(stored?.aiDecisionSnapshot?.source, "AI"); assert.equal(stored?.aiDecisionSnapshot?.similarity, similarity); assert.equal(stored?.aiDecisionSnapshot?.threshold, 0.9); assert.ok(stored?.aiDecisionSnapshot?.decidedAt instanceof Date); assert.equal((await UserProfile.findById(profile._id))?.profileStatus, "verified"); }
});
test("below-threshold and absent-threshold results require Admin review and never reject", async () => {
  for (const [suffix, input] of [["below", { similarity: 0.89, threshold: 0.9, conclusion: "LIKELY_MISMATCH" as const }], ["absent", { conclusion: "UNABLE_TO_DETERMINE" as const }]] as const) { const { profile, request } = await setup(suffix); await applyProfileVerificationAiDecision({ request, result: await result(request, input) }); const stored = await ProfileVerificationRequest.findById(request._id); assert.equal(stored?.status, "ADMIN_REVIEW_REQUIRED"); assert.equal(stored?.decision, undefined); assert.equal((await UserProfile.findById(profile._id))?.profileStatus, "pending_verification"); }
});
test("an inference/request authority mismatch cannot approve or persist an AI snapshot", async () => { const { profile, request } = await setup("mismatch"); await applyProfileVerificationAiDecision({ request, result: await result(request, { similarity: 0.95, threshold: 0.9, conclusion: "LIKELY_MATCH", mismatch: true }) }); const stored = await ProfileVerificationRequest.findById(request._id); assert.equal(stored?.status, "ADMIN_REVIEW_REQUIRED"); assert.equal(stored?.aiDecisionSnapshot, undefined); assert.equal((await UserProfile.findById(profile._id))?.profileStatus, "pending_verification"); });
test("a persisted gated request never enters the legacy .90 approval authority", async () => { const previousThreshold = process.env.STHN_SFACE_IDENTITY_APPROVAL_THRESHOLD; process.env.STHN_SFACE_IDENTITY_APPROVAL_THRESHOLD = "0.90"; try { const { profile, request } = await setup("gated-high", true); delete process.env.STHN_PROFILE_VERIFICATION_POLICY; await applyProfileVerificationAiDecision({ request, result: await result(request, { similarity: 0.99, threshold: 0.9, conclusion: "LIKELY_MATCH" }) }); const stored = await ProfileVerificationRequest.findById(request._id); assert.equal(stored?.verificationPolicy?.key, "GATED_MULTI_MEDIA"); assert.equal(stored?.verificationPolicy?.version, "V1"); assert.equal(stored?.status, "ADMIN_REVIEW_REQUIRED"); assert.equal(stored?.decision, undefined); assert.equal(stored?.aiDecisionSnapshot, undefined); assert.equal((await UserProfile.findById(profile._id))?.profileStatus, "pending_verification"); } finally { if (previousThreshold === undefined) delete process.env.STHN_SFACE_IDENTITY_APPROVAL_THRESHOLD; else process.env.STHN_SFACE_IDENTITY_APPROVAL_THRESHOLD = previousThreshold; } });
