// backend/src/enums/financial/auditAction.enum.ts

/**
 * Canonical audit actions for the Financial Domain.
 *
 * Every auditable financial operation should record one of these actions.
 * Audit records are immutable and provide a complete history of financial
 * activity for compliance, reporting, reconciliation, and investigations.
 */
export enum AuditAction {
  /* =========================================================
     Payment
  ========================================================= */

  PAYMENT_CREATED = "PAYMENT_CREATED",
  PAYMENT_INITIALIZED = "PAYMENT_INITIALIZED",
  PAYMENT_PROVIDER_SYNCHRONIZED = "PAYMENT_PROVIDER_SYNCHRONIZED",
  PAYMENT_OUTCOME_UNKNOWN = "PAYMENT_OUTCOME_UNKNOWN",
  PAYMENT_REPLAY_DETECTED = "PAYMENT_REPLAY_DETECTED",
  PAYMENT_AUTHORIZED = "PAYMENT_AUTHORIZED",
  PAYMENT_CAPTURED = "PAYMENT_CAPTURED",
  PAYMENT_SETTLED = "PAYMENT_SETTLED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_CANCELLED = "PAYMENT_CANCELLED",
  PAYMENT_EXPIRED = "PAYMENT_EXPIRED",
  BOOKING_WALLET_RESERVATION_RELEASED = "BOOKING_WALLET_RESERVATION_RELEASED",
  BOOKING_WALLET_RESERVATION_CAPTURED = "BOOKING_WALLET_RESERVATION_CAPTURED",
  BOOKING_ESCROW_ALLOCATED = "BOOKING_ESCROW_ALLOCATED",
  BOOKING_CREATOR_WALLET_SETTLED = "BOOKING_CREATOR_WALLET_SETTLED",
  BOOKING_CREATOR_SETTLEMENT_RECONCILED = "BOOKING_CREATOR_SETTLEMENT_RECONCILED",
  BOOKING_CREATOR_SETTLEMENT_RETRIED = "BOOKING_CREATOR_SETTLEMENT_RETRIED",
  BOOKING_CREATOR_SETTLEMENT_REPAIRED = "BOOKING_CREATOR_SETTLEMENT_REPAIRED",
  PAYMENT_RETRIED = "PAYMENT_RETRIED",

  /* =========================================================
     Refund
  ========================================================= */

  REFUND_CREATED = "REFUND_CREATED",
  REFUND_APPROVED = "REFUND_APPROVED",
  REFUND_REJECTED = "REFUND_REJECTED",
  REFUND_COMPLETED = "REFUND_COMPLETED",
  REFUND_FAILED = "REFUND_FAILED",
  REFUND_REQUESTED = "REFUND_REQUESTED",
  REFUND_PROVIDER_INITIATED = "REFUND_PROVIDER_INITIATED",
  REFUND_PROVIDER_SYNCHRONIZED = "REFUND_PROVIDER_SYNCHRONIZED",
  REFUND_OUTCOME_UNKNOWN = "REFUND_OUTCOME_UNKNOWN",
  REFUND_REPLAY_DETECTED = "REFUND_REPLAY_DETECTED",
  ESCROW_FUNDS_RECOGNIZED = "ESCROW_FUNDS_RECOGNIZED",

  /* =========================================================
     Settlement
  ========================================================= */

  SETTLEMENT_CREATED = "SETTLEMENT_CREATED",
  SETTLEMENT_COMPLETED = "SETTLEMENT_COMPLETED",
  SETTLEMENT_FAILED = "SETTLEMENT_FAILED",
  SETTLEMENT_ELIGIBILITY_BLOCKED = "SETTLEMENT_ELIGIBILITY_BLOCKED",
  SETTLEMENT_STARTED = "SETTLEMENT_STARTED",
  SETTLEMENT_REPLAY_DETECTED = "SETTLEMENT_REPLAY_DETECTED",
  SETTLEMENT_CONFLICT_DETECTED = "SETTLEMENT_CONFLICT_DETECTED",

  /* =========================================================
     Payability
  ========================================================= */

  BOOKING_MARKED_PAYABLE = "BOOKING_MARKED_PAYABLE",
  BOOKING_PAYABILITY_REVOKED = "BOOKING_PAYABILITY_REVOKED",

  /* =========================================================
     Payout
  ========================================================= */

  PAYOUT_CREATED = "PAYOUT_CREATED",
  PAYOUT_COMPLETED = "PAYOUT_COMPLETED",
  PAYOUT_FAILED = "PAYOUT_FAILED",
  PAYOUT_CANCELLED = "PAYOUT_CANCELLED",
  PAYOUT_PROCESS_REQUESTED = "PAYOUT_PROCESS_REQUESTED",
  PAYOUT_PROCESSING_STARTED = "PAYOUT_PROCESSING_STARTED",
  PAYOUT_PROVIDER_REQUESTED = "PAYOUT_PROVIDER_REQUESTED",
  PAYOUT_PROVIDER_SYNCHRONIZED = "PAYOUT_PROVIDER_SYNCHRONIZED",
  PAYOUT_SUCCEEDED = "PAYOUT_SUCCEEDED",
  PAYOUT_OUTCOME_UNKNOWN = "PAYOUT_OUTCOME_UNKNOWN",
  PAYOUT_REPLAY_DETECTED = "PAYOUT_REPLAY_DETECTED",
  WITHDRAWAL_REQUESTED = "WITHDRAWAL_REQUESTED",
  CREATOR_WITHDRAWAL_REQUESTED = "CREATOR_WITHDRAWAL_REQUESTED",
  CREATOR_WITHDRAWAL_PROVIDER_INITIALIZED =
    "CREATOR_WITHDRAWAL_PROVIDER_INITIALIZED",
  CREATOR_WITHDRAWAL_PROVIDER_PROCESSING =
    "CREATOR_WITHDRAWAL_PROVIDER_PROCESSING",
  CREATOR_WITHDRAWAL_PROVIDER_SUCCEEDED =
    "CREATOR_WITHDRAWAL_PROVIDER_SUCCEEDED",
  CREATOR_WITHDRAWAL_PROVIDER_FAILED =
    "CREATOR_WITHDRAWAL_PROVIDER_FAILED",
  CREATOR_WITHDRAWAL_COMPLETED = "CREATOR_WITHDRAWAL_COMPLETED",
  CREATOR_WITHDRAWAL_FAILED = "CREATOR_WITHDRAWAL_FAILED",
  CREATOR_WITHDRAWAL_RECONCILIATION_CREATED =
    "CREATOR_WITHDRAWAL_RECONCILIATION_CREATED",
  CREATOR_WITHDRAWAL_FINALIZATION_RETRIED =
    "CREATOR_WITHDRAWAL_FINALIZATION_RETRIED",
  CREATOR_WITHDRAWAL_METADATA_REPAIRED =
    "CREATOR_WITHDRAWAL_METADATA_REPAIRED",
  CREATOR_WITHDRAWAL_RECONCILIATION_ACKNOWLEDGED =
    "CREATOR_WITHDRAWAL_RECONCILIATION_ACKNOWLEDGED",
  CREATOR_WITHDRAWAL_RECONCILIATION_RESOLVED =
    "CREATOR_WITHDRAWAL_RECONCILIATION_RESOLVED",
  WITHDRAWAL_FUNDS_RESERVED = "WITHDRAWAL_FUNDS_RESERVED",
  WITHDRAWAL_CANCELLED = "WITHDRAWAL_CANCELLED",
  WITHDRAWAL_RESERVATION_RELEASED = "WITHDRAWAL_RESERVATION_RELEASED",

  /* =========================================================
     Ledger
  ========================================================= */

  LEDGER_ENTRY_CREATED = "LEDGER_ENTRY_CREATED",

  /* =========================================================
     Balance
  ========================================================= */

  CREATOR_BALANCE_UPDATED = "CREATOR_BALANCE_UPDATED",

  /* =========================================================
     Financial Locks
  ========================================================= */

  FINANCIAL_LOCK_APPLIED = "FINANCIAL_LOCK_APPLIED",
  FINANCIAL_LOCK_RELEASED = "FINANCIAL_LOCK_RELEASED",

  /* =========================================================
     Administrative
  ========================================================= */

  MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT",
  MANUAL_CORRECTION = "MANUAL_CORRECTION",
  ADMIN_PAYMENT_SYNC_REQUESTED = "ADMIN_PAYMENT_SYNC_REQUESTED",
  ADMIN_REFUND_SYNC_REQUESTED = "ADMIN_REFUND_SYNC_REQUESTED",
  ADMIN_SETTLEMENT_RECHECK_REQUESTED = "ADMIN_SETTLEMENT_RECHECK_REQUESTED",
  ADMIN_WITHDRAWAL_PROCESS_REQUESTED = "ADMIN_WITHDRAWAL_PROCESS_REQUESTED",
  ADMIN_WITHDRAWAL_SYNC_REQUESTED = "ADMIN_WITHDRAWAL_SYNC_REQUESTED",
  ADMIN_PAYOUT_SYNC_REQUESTED = "ADMIN_PAYOUT_SYNC_REQUESTED",
  ADMIN_BOOKING_ESCROW_MANUAL_RELEASED = "ADMIN_BOOKING_ESCROW_MANUAL_RELEASED",

  /* =========================================================
     Reconciliation
  ========================================================= */

  RECONCILIATION_STARTED = "RECONCILIATION_STARTED",
  RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED",
  RECONCILIATION_FAILED = "RECONCILIATION_FAILED",
  WITHDRAWAL_RECONCILIATION_APPLIED = "WITHDRAWAL_RECONCILIATION_APPLIED",
  WITHDRAWAL_RECONCILIATION_CONFLICT = "WITHDRAWAL_RECONCILIATION_CONFLICT",
}
