export enum BookingWalletReleaseCause {
  CREATOR_REJECTED = "CREATOR_REJECTED",
  REQUEST_EXPIRED = "REQUEST_EXPIRED",
  USER_CANCELLED = "USER_CANCELLED",
  CREATOR_CANCELLED = "CREATOR_CANCELLED",
  ADMIN_CANCELLED = "ADMIN_CANCELLED",
  GOVERNANCE_TERMINATED = "GOVERNANCE_TERMINATED",
}
