export enum BookingCreatorSettlementFailureClassification {
  HEALTHY = "HEALTHY",
  REPLAY_REQUIRED = "REPLAY_REQUIRED",
  PENDING = "PENDING",
  CORRUPTED_LEDGER = "CORRUPTED_LEDGER",
  CORRUPTED_PROJECTION = "CORRUPTED_PROJECTION",
  CORRUPTED_SETTLEMENT = "CORRUPTED_SETTLEMENT",
  MISSING_AUDIT = "MISSING_AUDIT",
  INTEGRITY_FAILURE = "INTEGRITY_FAILURE",
  UNKNOWN = "UNKNOWN",
}
