export enum CreatorWithdrawalOperationalAction {
  INSPECT = "INSPECT",
  RETRY_FINALIZATION = "RETRY_FINALIZATION",
  RESTORE_FINALIZATION_LINKS = "RESTORE_FINALIZATION_LINKS",
  RESTORE_TERMINAL_AUDIT = "RESTORE_TERMINAL_AUDIT",
  ACKNOWLEDGE = "ACKNOWLEDGE",
  RESOLVE = "RESOLVE",
}
