export enum FinancialReconciliationReason {
  MISSING_PAYMENT = "MISSING_PAYMENT",
  MULTIPLE_MATCHING_PAYMENTS = "MULTIPLE_MATCHING_PAYMENTS",
  MISSING_BOOKING_AMOUNT = "MISSING_BOOKING_AMOUNT",
  MISSING_CAPTURED_AMOUNT = "MISSING_CAPTURED_AMOUNT",
  AMOUNT_MISMATCH = "AMOUNT_MISMATCH",
  CURRENCY_MISMATCH = "CURRENCY_MISMATCH",
  LEDGER_CONFLICT = "LEDGER_CONFLICT",
  PAYMENT_STATUS_UNSUPPORTED = "PAYMENT_STATUS_UNSUPPORTED",
  REFUND_STATE_AMBIGUOUS = "REFUND_STATE_AMBIGUOUS",
  RELATIONSHIP_CONFLICT = "RELATIONSHIP_CONFLICT",
  UNSUPPORTED_LEGACY_STATE = "UNSUPPORTED_LEGACY_STATE",
}
