export enum FxRateAuditAction {
  SNAPSHOT_CREATED = "FX_RATE_SNAPSHOT_CREATED",
  SNAPSHOT_REUSED = "FX_RATE_SNAPSHOT_REUSED",
  SNAPSHOT_SUPERSEDED = "FX_RATE_SNAPSHOT_SUPERSEDED",
  REFRESH_FAILED = "FX_RATE_REFRESH_FAILED",
}
