/**
 * Financial ownership buckets.  Entries are immutable; an account balance is
 * derived from credits less debits for the same currency.
 */
export enum LedgerAccount {
  WALLET_TOP_UP = "WALLET_TOP_UP",
  WALLET_AVAILABLE = "WALLET_AVAILABLE",
  WALLET_RESERVED = "WALLET_RESERVED",
  WITHDRAWAL_RESERVED = "WITHDRAWAL_RESERVED",
  CASH = "CASH",
  CUSTOMER_CAPTURE = "CUSTOMER_CAPTURE",
  PLATFORM_ESCROW = "PLATFORM_ESCROW",
  PLATFORM_COMMISSION_PAYABLE = "PLATFORM_COMMISSION_PAYABLE",
  PLATFORM_SERVICE_FEE_REVENUE = "PLATFORM_SERVICE_FEE_REVENUE",
  CREATOR_PAYABLE = "CREATOR_PAYABLE",
  CUSTOMER_REFUND = "CUSTOMER_REFUND",
  CREATOR_AVAILABLE = "CREATOR_AVAILABLE",
  CREATOR_PAYOUT_RESERVED = "CREATOR_PAYOUT_RESERVED",
  PAYOUT_CLEARING = "PAYOUT_CLEARING",
  PLATFORM_CUSTOMER_FEE_REVENUE = "PLATFORM_CUSTOMER_FEE_REVENUE",
  PLATFORM_CREATOR_COMMISSION_REVENUE = "PLATFORM_CREATOR_COMMISSION_REVENUE",
}
