export enum WalletConversionOperationalIssue {
  NONE = "NONE",
  ACCOUNTING_COMPLETION_REPLAY_REQUIRED =
    "ACCOUNTING_COMPLETION_REPLAY_REQUIRED",
  ACCOUNTING_REFERENCES_MISSING = "ACCOUNTING_REFERENCES_MISSING",
  LEDGER_REFERENCES_MISSING = "LEDGER_REFERENCES_MISSING",
  PROJECTION_REFERENCES_MISSING = "PROJECTION_REFERENCES_MISSING",
  TERMINAL_AUDIT_MISSING = "TERMINAL_AUDIT_MISSING",
  REQUEST_IDENTITY_CONFLICT = "REQUEST_IDENTITY_CONFLICT",
  SNAPSHOT_CONFLICT = "SNAPSHOT_CONFLICT",
  PROVIDER_CONFLICT = "PROVIDER_CONFLICT",
  LEDGER_CONFLICT = "LEDGER_CONFLICT",
  PROJECTION_CONFLICT = "PROJECTION_CONFLICT",
  WALLET_INVARIANT_CONFLICT = "WALLET_INVARIANT_CONFLICT",
  AUDIT_CONFLICT = "AUDIT_CONFLICT",
  UNKNOWN_CONFLICT = "UNKNOWN_CONFLICT",
}
