export enum WalletConversionAuditAction {
  REQUEST_CREATED = "WALLET_CONVERSION_REQUEST_CREATED",
  APPROVED = "WALLET_CONVERSION_APPROVED",
  REJECTED = "WALLET_CONVERSION_REJECTED",
  PROVIDER_STARTED = "WALLET_CONVERSION_PROVIDER_STARTED",
  PROVIDER_SUCCEEDED = "WALLET_CONVERSION_PROVIDER_SUCCEEDED",
  PROVIDER_FAILED = "WALLET_CONVERSION_PROVIDER_FAILED",
  COMPLETED = "WALLET_CONVERSION_COMPLETED",
  FAILED = "WALLET_CONVERSION_FAILED",
  RECONCILED = "WALLET_CONVERSION_RECONCILED",
  RETRY = "WALLET_CONVERSION_RETRY",
  REPAIRED = "WALLET_CONVERSION_REPAIRED",
}
