export enum WalletTopUpOperationalAction {
  INSPECT = "INSPECT",
  FINALIZE_PROVIDER_FAILURE = "FINALIZE_PROVIDER_FAILURE",
  RETRY_ACCOUNTING = "RETRY_ACCOUNTING",
  RETRY_COMPLETION = "RETRY_COMPLETION",
  MARK_RECONCILIATION_REQUIRED = "MARK_RECONCILIATION_REQUIRED",
  REPAIR_REQUEST_LINKS = "REPAIR_REQUEST_LINKS",
  REPAIR_PROJECTION_LINK = "REPAIR_PROJECTION_LINK",
  REPAIR_LEDGER_LINK = "REPAIR_LEDGER_LINK",
  ACKNOWLEDGE_CORRUPTION = "ACKNOWLEDGE_CORRUPTION",
  RESOLVE_RECONCILIATION = "RESOLVE_RECONCILIATION",
}
