export enum WalletConversionRepairAction {
  RESTORE_MISSING_AUDIT = "RESTORE_MISSING_AUDIT",
  RESTORE_LEDGER_REFERENCES = "RESTORE_LEDGER_REFERENCES",
  RESTORE_PROJECTION_REFERENCES = "RESTORE_PROJECTION_REFERENCES",
  RESTORE_ACCOUNTING_REFERENCES = "RESTORE_ACCOUNTING_REFERENCES",
}
