export enum WalletConversionOperationalClassification {
  HEALTHY = "HEALTHY",
  REPLAY_REQUIRED = "REPLAY_REQUIRED",
  PENDING = "PENDING",
  CORRUPTED_LEDGER = "CORRUPTED_LEDGER",
  CORRUPTED_PROJECTION = "CORRUPTED_PROJECTION",
  CORRUPTED_REQUEST = "CORRUPTED_REQUEST",
  CORRUPTED_PROVIDER = "CORRUPTED_PROVIDER",
  CORRUPTED_SNAPSHOT = "CORRUPTED_SNAPSHOT",
  MISSING_AUDIT = "MISSING_AUDIT",
  INTEGRITY_FAILURE = "INTEGRITY_FAILURE",
  UNKNOWN = "UNKNOWN",
}
