export enum WalletConversionRejectionCode {
  ADMIN_DECLINED = "ADMIN_DECLINED",
  INVALID_REQUEST = "INVALID_REQUEST",
  FX_SNAPSHOT_NOT_ACCEPTABLE = "FX_SNAPSHOT_NOT_ACCEPTABLE",
  INSUFFICIENT_SOURCE_FUNDS = "INSUFFICIENT_SOURCE_FUNDS",
  SIMULATION_REJECTED = "SIMULATION_REJECTED",
  OTHER = "OTHER",
}
