export enum WithdrawalEligibilityReason {
  INVALID_AMOUNT = "INVALID_AMOUNT",
  CREATOR_INACTIVE = "CREATOR_INACTIVE",
  GOVERNANCE_BLOCK = "GOVERNANCE_BLOCK",
  NO_VERIFIED_DESTINATION = "NO_VERIFIED_DESTINATION",
  UNSUPPORTED_CURRENCY = "UNSUPPORTED_CURRENCY",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  PENDING_WITHDRAWAL = "PENDING_WITHDRAWAL",
}
