import assert from "node:assert/strict";
import { after, before, beforeEach, test } from "node:test";
import { Types } from "mongoose";
import type { Request, Response } from "express";
import User from "../../models/User";
import { UserProfile } from "../../models/userProfile.model";
import { CreatorProfile } from "../../models/creatorProfile.model";
import { Booking } from "../../models/booking.model";
import { Dispute } from "../../models/dispute.model";
import { Chat } from "../../models/chat.model";
import { Review } from "../../models/review.model";
import { ModerationQueue } from "../../models/moderationQueue.model";
import { DisputeDirectEvidence } from "../../models/disputeDirectEvidence.model";
import { DisputeAdminRequest } from "../../models/disputeAdminRequest.model";
import { getAdminDisputeInvestigation } from "../../controllers/adminDispute.controller";
import { clearPhase7HDatabase, connectPhase7HDatabase, disconnectPhase7HDatabase } from "../financial/phase7h/helpers/database";
process.env.NODE_ENV="test";
before(async()=>connectPhase7HDatabase(),{timeout:120000});beforeEach(async()=>clearPhase7HDatabase());after(async()=>disconnectPhase7HDatabase(),{timeout:30000});
function response(){const result:{body?:any;statusCode?:number;response:Response}={} as never;result.response={status:(code:number)=>{result.statusCode=code;return result.response},json:(body:unknown)=>{result.body=body;return result.response}} as unknown as Response;return result;}
async function fixture(snapshot=true){const suffix=new Types.ObjectId().toString();const [customer,creator,other]=await Promise.all([User.create({email:`di3-u-${suffix}@x.test`,password:"x",status:"active",governanceState:"ACTIVE",abuseScore:3}),User.create({email:`di3-c-${suffix}@x.test`,password:"x",status:"active",governanceState:"ACTIVE"}),User.create({email:`di3-o-${suffix}@x.test`,password:"x",status:"active",governanceState:"ACTIVE"})]);await UserProfile.create({userId:customer._id,username:`customer-${suffix}`,dateOfBirth:new Date("1990-01-01"),interests:[],bio:"bio",avatar:"avatar",cover:"cover",profilePhotos:["a","b"],profileStatus:"verified"});await CreatorProfile.create({userId:creator._id,slug:`creator-${suffix}`,displayName:"Creator",primaryCategory:"Music",country:"IN",city:"Delhi",currency:"USD",status:"active"});const booking=await Booking.create({slotIds:[new Types.ObjectId()],userId:customer._id,creatorId:creator._id,serviceId:new Types.ObjectId(),...(snapshot?{serviceSnapshot:{serviceId:new Types.ObjectId(),title:"Historical",description:"original",durationMinutes:30,price:20,currency:"USD",media:["media"]}}:{}),serviceTitle:"Legacy title",durationMinutes:30,price:2000,currency:"USD",status:"COMPLETED",paymentStatus:"PAID",isPayable:true,isPayoutEligible:false,isFinancialLocked:false,expiresAt:new Date(),hasInteracted:true,serviceAmount:2000,platformFeeAmount:0,commissionAmount:400,creatorAmount:1600,totalAmount:2000,completedAt:new Date()});const otherBooking=await Booking.create({...booking.toObject(),_id:new Types.ObjectId(),bookingReference:undefined,slotIds:[new Types.ObjectId()],userId:other._id,serviceId:new Types.ObjectId()});const dispute=await Dispute.create({bookingId:booking._id,raisedBy:customer._id,raisedByRole:"USER",reason:"Claim",status:"OPEN"});return{customer,creator,other,booking,otherBooking,dispute};}
async function read(id:string,limit="50"){const r=response();await getAdminDisputeInvestigation({params:{disputeId:id},query:{limit}} as unknown as Request,r.response);return r.body;}
test("DI-3 composes only disputed-booking identities, immutable snapshot, chat, review, moderation, direct evidence and bounded history",async()=>{const f=await fixture();await Promise.all([Chat.create({bookingId:f.booking._id,senderId:f.customer._id,senderRole:"USER",type:"text",message:"preserved",seenBy:[],aiFlags:["FLAG"],isDeleted:true,deletedAt:new Date(),reactions:[]}),Chat.create({bookingId:f.otherBooking._id,senderId:f.other._id,senderRole:"USER",type:"text",message:"leak",seenBy:[],aiFlags:[],isDeleted:false,reactions:[]}),Review.create({bookingId:f.booking._id,reviewerId:f.customer._id,revieweeId:f.creator._id,role:"USER_TO_CREATOR",rating:4,comment:"review",verified:true,trustScore:1,reports:0,isFlagged:false}),ModerationQueue.create({bookingId:f.booking._id,chatId:new Types.ObjectId(),offenderId:f.customer._id,severity:"LOW",reasons:["flag"],reviewed:false}),DisputeDirectEvidence.create({disputeId:f.dispute._id,bookingId:f.booking._id,source:"CUSTOMER",uploadedBy:f.customer._id,type:"IMAGE",url:"https://safe",publicId:"hidden",fileName:"proof",mimeType:"image/png",fileSize:1}),DisputeAdminRequest.create({disputeId:f.dispute._id,requestedBy:f.creator._id,target:"BOTH",text:"clarify"})]);const body=await read(String(f.dispute._id));assert.equal(body.context.customer.userId,String(f.customer._id));assert.equal(body.context.creator.userId,String(f.creator._id));assert.equal(body.context.booking.serviceSnapshot.title,"Historical");assert.equal(body.context.chat.messages.length,1);assert.equal(body.context.chat.messages[0].isDeleted,true);assert.equal(body.context.reviews.length,1);assert.equal(body.context.moderation.length,1);assert.equal(body.directEvidence[0].source,"CUSTOMER");assert.equal(body.sharedAdminRequests.length,1);assert.equal(JSON.stringify(body).includes("publicId"),false);assert.equal(JSON.stringify(body).includes("password"),false);});
test("DI-3 retains legacy immutable booking fields without fabricating a live snapshot and safely handles absent optional context",async()=>{const f=await fixture(false);const body=await read(String(f.dispute._id));assert.equal(body.context.booking.serviceSnapshot,null);assert.equal(body.context.booking.serviceTitle,"Legacy title");assert.equal(body.context.reviews.length,0);assert.equal(body.context.moderation.length,0);assert.equal(body.context.chat.messages.length,0);assert.equal(body.context.customer.profileStatus,"verified");});
test("DI-3 investigation limits chat and rejects invalid or absent disputes through current bounded errors",async()=>{const f=await fixture();for(let i=0;i<4;i++)await Chat.create({bookingId:f.booking._id,senderId:f.customer._id,senderRole:"USER",type:"text",message:String(i),seenBy:[],aiFlags:[],isDeleted:false,reactions:[]});assert.equal((await read(String(f.dispute._id),"2")).context.chat.messages.length,2);await assert.rejects(()=>read("invalid"),/Invalid disputeId/);await assert.rejects(()=>read(String(new Types.ObjectId())),/Dispute not found/);});
