import assert from "node:assert/strict";
import { after, before, beforeEach, test } from "node:test";
import { Types } from "mongoose";
import type { Request, Response } from "express";
import User from "../../models/User";
import { AuditLog } from "../../models/auditLog.model";
import { Booking } from "../../models/booking.model";
import { Chat } from "../../models/chat.model";
import { Dispute } from "../../models/dispute.model";
import { DisputeInvestigationSubmission } from "../../models/disputeInvestigationSubmission.model";
import { createAdminDisputeRequest, getAdminDisputeInvestigation, shareAdminDisputeSubmission } from "../../controllers/adminDispute.controller";
import { createParticipantSubmission, getParticipantInvestigation } from "../../controllers/disputeInvestigation.controller";
import { clearPhase7HDatabase, connectPhase7HDatabase, disconnectPhase7HDatabase } from "../financial/phase7h/helpers/database";

process.env.NODE_ENV = "test";
before(async () => connectPhase7HDatabase(), { timeout: 120_000 }); beforeEach(async () => clearPhase7HDatabase()); after(async () => disconnectPhase7HDatabase(), { timeout: 30_000 });
function response() { const r: { body?: any; statusCode?: number; response: Response } = {} as never; r.response = { status: (n: number) => { r.statusCode = n; return r.response; }, json: (b: unknown) => { r.body = b; return r.response; } } as unknown as Response; return r; }
async function fixture() { const id = new Types.ObjectId().toString(); const [customer, creator, admin] = await Promise.all([User.create({ email: `di2c-u-${id}@x.test`, password: "x", status: "active", governanceState: "ACTIVE" }), User.create({ email: `di2c-c-${id}@x.test`, password: "x", status: "active", governanceState: "ACTIVE" }), User.create({ email: `di2c-a-${id}@x.test`, password: "x", role: "admin", status: "active", governanceState: "ACTIVE" })]); const booking = await Booking.create({ slotIds: [new Types.ObjectId()], userId: customer._id, creatorId: creator._id, serviceId: new Types.ObjectId(), serviceTitle: "Evidence", durationMinutes: 30, price: 100, currency: "INR", status: "CANCELLED", paymentStatus: "PAID", isPayable: true, isPayoutEligible: false, isFinancialLocked: false, expiresAt: new Date(Date.now()+999999), hasInteracted: true, serviceAmount:100, platformFeeAmount:0, commissionAmount:20, creatorAmount:80, totalAmount:100 }); const dispute = await Dispute.create({ bookingId: booking._id, raisedBy: customer._id, raisedByRole:"USER", reason:"Investigation", status:"OPEN" }); return { customer, creator, admin, booking, dispute }; }
async function submit(actor: any, disputeId: string, body: any) { const r=response(); await createParticipantSubmission({ user:{id:String(actor._id)}, params:{disputeId}, body } as unknown as Request,r.response); return r; }
async function read(actor: any, disputeId: string) { const r=response(); await getParticipantInvestigation({user:{id:String(actor._id)},params:{disputeId},query:{}} as unknown as Request,r.response); return r.body; }

test("DI-2C creates append-only private participant submissions and preserves supported Chat evidence", async () => { const f=await fixture(); const attachment=await Chat.create({ bookingId:f.booking._id,senderId:f.customer._id,senderRole:"USER",type:"image",message:"proof",attachment:{url:"https://res.cloudinary.com/test/image/upload/v1/proof.jpg",publicId:"proof",fileName:"proof",originalFileName:"proof.jpg",mimeType:"image/jpeg",fileSize:9,resourceType:"image"},seenBy:[f.customer._id],aiFlags:[],isDeleted:false,reactions:[] }); const made=await submit(f.customer,String(f.dispute._id),{kind:"EVIDENCE",text:"My evidence",evidence:[{chatMessageId:String(attachment._id),caption:"receipt"}],submittedBy:"ADMIN",sharedWithCounterparty:true}); assert.equal(made.statusCode,201); assert.equal(made.body.submission.branch,"CUSTOMER"); assert.equal(made.body.submission.evidence[0].type,"IMAGE"); assert.equal(await DisputeInvestigationSubmission.countDocuments({disputeId:f.dispute._id}),1); await assert.rejects(()=>submit(f.creator,String(f.dispute._id),{kind:"EVIDENCE",evidence:[{chatMessageId:String(attachment._id)}]}),/Evidence must reference your existing/); });

test("DI-2C enforces branch controls and hides unshared counterparty content", async () => { const f=await fixture(); await submit(f.customer,String(f.dispute._id),{kind:"STATEMENT",text:"customer private"}); await submit(f.creator,String(f.dispute._id),{kind:"STATEMENT",text:"creator private"}); const customer=await read(f.customer,String(f.dispute._id)); const creator=await read(f.creator,String(f.dispute._id)); assert.equal(customer.submissions.length,1); assert.equal(creator.submissions.length,1); assert.equal(customer.submissions[0].branch,"CUSTOMER"); assert.equal(creator.submissions[0].branch,"CREATOR"); f.dispute.customerInput.state="CLOSED"; await f.dispute.save(); await assert.rejects(()=>submit(f.customer,String(f.dispute._id),{kind:"STATEMENT",text:"blocked"}),/input is closed/); });

test("DI-2C Admin requests are target-filtered and explicit sharing is item-specific and replay-safe", async () => { const f=await fixture(); const first=await submit(f.customer,String(f.dispute._id),{kind:"STATEMENT",text:"share me"}); await submit(f.customer,String(f.dispute._id),{kind:"STATEMENT",text:"do not share"}); const request=response(); await createAdminDisputeRequest({user:{id:String(f.admin._id),role:"admin"},params:{disputeId:String(f.dispute._id)},body:{target:"CUSTOMER",text:"Please clarify"}} as unknown as Request,request.response); assert.equal(request.statusCode,201); assert.equal((await read(f.customer,String(f.dispute._id))).adminRequests.length,1); assert.equal((await read(f.creator,String(f.dispute._id))).adminRequests.length,0); const share=response(); await shareAdminDisputeSubmission({user:{id:String(f.admin._id),role:"admin"},params:{disputeId:String(f.dispute._id)},body:{submissionReference:first.body.submission.submissionReference}} as unknown as Request,share.response); assert.equal(share.body.changed,true); const creator=await read(f.creator,String(f.dispute._id)); assert.equal(creator.submissions.length,1); assert.equal(creator.submissions[0].text,"share me"); const replay=response(); await shareAdminDisputeSubmission({user:{id:String(f.admin._id),role:"admin"},params:{disputeId:String(f.dispute._id)},body:{submissionReference:first.body.submission.submissionReference}} as unknown as Request,replay.response); assert.equal(replay.body.changed,false); assert.equal(await AuditLog.countDocuments({action:"DISPUTE_SUBMISSION_SHARED",entityId:f.dispute._id}),1); const adminRead=response(); await getAdminDisputeInvestigation({params:{disputeId:String(f.dispute._id)},query:{}} as unknown as Request,adminRead.response); assert.equal(adminRead.body.customerBranch.length,2); });

test("DI-2C terminal disputes reject submissions, requests, and sharing without financial or governance changes", async () => { const f=await fixture(); const item=await submit(f.customer,String(f.dispute._id),{kind:"STATEMENT",text:"existing"}); f.dispute.status="REJECTED"; await f.dispute.save(); await assert.rejects(()=>submit(f.customer,String(f.dispute._id),{kind:"STATEMENT",text:"blocked"}),/OPEN dispute/); await assert.rejects(()=>createAdminDisputeRequest({user:{id:String(f.admin._id),role:"admin"},params:{disputeId:String(f.dispute._id)},body:{target:"BOTH",text:"blocked"}} as unknown as Request,response().response),/OPEN dispute/); await assert.rejects(()=>shareAdminDisputeSubmission({user:{id:String(f.admin._id),role:"admin"},params:{disputeId:String(f.dispute._id)},body:{submissionReference:item.body.submission.submissionReference}} as unknown as Request,response().response),/OPEN dispute/); assert.equal((await User.findById(f.customer._id).lean())?.governanceState,"ACTIVE"); assert.equal((await Booking.findById(f.booking._id).lean())?.status,"CANCELLED"); });
