import assert from "node:assert/strict";
import { after, before, beforeEach, test } from "node:test";
import { Types } from "mongoose";
import type { Request, Response } from "express";
import User from "../../models/User";
import { Booking } from "../../models/booking.model";
import { Dispute } from "../../models/dispute.model";
import { DisputeFinding } from "../../models/disputeFinding.model";
import { AuditLog } from "../../models/auditLog.model";
import { Refund } from "../../models/refund.model";
import { LedgerEntry } from "../../models/ledgerEntry.model";
import { addAdminDisputeFinding, finalizeAdminDispute, getAdminDisputeInvestigation } from "../../controllers/adminDispute.controller";
import { getBookingDisputeState } from "../../controllers/dispute.controller";
import { clearPhase7HDatabase, connectPhase7HDatabase, disconnectPhase7HDatabase } from "../financial/phase7h/helpers/database";

process.env.NODE_ENV = "test";
before(async () => connectPhase7HDatabase(), { timeout: 120000 });
beforeEach(async () => clearPhase7HDatabase());
after(async () => disconnectPhase7HDatabase(), { timeout: 30000 });

function response() { const value: { body?: unknown; statusCode?: number; response: Response } = {} as never; value.response = { status: (code: number) => { value.statusCode = code; return value.response; }, json: (body: unknown) => { value.body = body; return value.response; } } as unknown as Response; return value; }
async function fixture() { const suffix = new Types.ObjectId().toString(); const [admin, customer, creator] = await Promise.all([User.create({ email: `admin-${suffix}@test`, password: "x", role: "admin", status: "active", governanceState: "ACTIVE" }), User.create({ email: `customer-${suffix}@test`, password: "x", status: "active", governanceState: "ACTIVE" }), User.create({ email: `creator-${suffix}@test`, password: "x", role: "creator", status: "active", governanceState: "ACTIVE" })]); const booking = await Booking.create({ slotIds: [new Types.ObjectId()], userId: customer._id, creatorId: creator._id, serviceId: new Types.ObjectId(), serviceTitle: "Test", durationMinutes: 30, price: 1000, currency: "USD", status: "COMPLETED", paymentStatus: "PAID", isPayable: true, isPayoutEligible: false, isFinancialLocked: false, expiresAt: new Date(), hasInteracted: true, serviceAmount: 1000, platformFeeAmount: 0, commissionAmount: 200, creatorAmount: 800, totalAmount: 1000, completedAt: new Date() }); const dispute = await Dispute.create({ bookingId: booking._id, raisedBy: customer._id, raisedByRole: "USER", reason: "Issue", status: "OPEN" }); return { admin, customer, creator, booking, dispute }; }
function req(actor: { _id: Types.ObjectId; role: string }, disputeId: string, body: Record<string, unknown>) { return { params: { disputeId }, body, user: { id: String(actor._id), role: actor.role } } as unknown as Request; }

test("DI-4 findings are immutable, server-derived, admin-only, ordered, and financially/governance neutral", async () => { const f = await fixture(); const first = response(); await addAdminDisputeFinding(req(f.admin, String(f.dispute._id), { subject: "CUSTOMER", category: "SERVICE_DELIVERY", conclusion: "SUPPORTED", summary: "Customer statement supported." }), first.response); const second = response(); await addAdminDisputeFinding(req(f.admin, String(f.dispute._id), { subject: "CREATOR", category: "SERVICE_SCOPE", conclusion: "INCONCLUSIVE", summary: "Creator statement remains inconclusive." }), second.response); assert.equal(first.statusCode, 201); assert.equal(second.statusCode, 201); const findings = await DisputeFinding.find({ disputeId: f.dispute._id }).sort({ createdAt: 1, _id: 1 }).lean(); assert.equal(findings.length, 2); assert.equal(String(findings[0].bookingId), String(f.booking._id)); assert.equal(String(findings[0].createdBy), String(f.admin._id)); assert.deepEqual(findings.map(x => x.conclusion), ["SUPPORTED", "INCONCLUSIVE"]); await assert.rejects(() => addAdminDisputeFinding(req(f.customer, String(f.dispute._id), { subject: "CUSTOMER", category: "SERVICE_DELIVERY", conclusion: "SUPPORTED", summary: "x" }), response().response), /Forbidden/); await assert.rejects(() => addAdminDisputeFinding(req(f.admin, String(f.dispute._id), { subject: "NOPE", category: "SERVICE_DELIVERY", conclusion: "SUPPORTED", summary: "x" }), response().response), /Invalid finding/); await assert.rejects(() => addAdminDisputeFinding(req(f.admin, String(f.dispute._id), { subject: "CUSTOMER", category: "NOPE", conclusion: "SUPPORTED", summary: "x" }), response().response), /Invalid finding/); await assert.rejects(() => addAdminDisputeFinding(req(f.admin, String(f.dispute._id), { subject: "CUSTOMER", category: "SERVICE_DELIVERY", conclusion: "NOPE", summary: " " }), response().response), /Invalid finding/); assert.equal(await Refund.countDocuments(), 0); assert.equal(await LedgerEntry.countDocuments(), 0); });

test("DI-4 finalizes only after both inputs close, persists review flags, replays safely, and blocks new findings", async () => { const f = await fixture(); const body = { customerOutcome: "ADVERSE_FINDING", customerSummary: "Customer outcome.", creatorOutcome: "INCONCLUSIVE", creatorSummary: "Creator outcome.", summary: "Participant-safe summary.", financialReviewRequired: true, governanceReviewRequired: false }; await assert.rejects(() => finalizeAdminDispute(req(f.admin, String(f.dispute._id), body), response().response), /Both participant inputs/); await Dispute.updateOne({ _id: f.dispute._id }, { $set: { "customerInput.state": "CLOSED", "creatorInput.state": "CLOSED" } }); const out = response(); await finalizeAdminDispute(req(f.admin, String(f.dispute._id), body), out.response); assert.equal((out.body as { replayed: boolean }).replayed, false); const stored = await Dispute.findById(f.dispute._id).lean(); assert.equal(stored?.status, "RESOLVED"); assert.equal(stored?.finalDecision?.financialReviewRequired, true); assert.equal(stored?.finalDecision?.governanceReviewRequired, false); const replay = response(); await finalizeAdminDispute(req(f.admin, String(f.dispute._id), body), replay.response); assert.equal((replay.body as { replayed: boolean }).replayed, true); assert.equal(await AuditLog.countDocuments({ action: "DISPUTE_FINALIZED" }), 1); await assert.rejects(() => addAdminDisputeFinding(req(f.admin, String(f.dispute._id), { subject: "BOTH", category: "OTHER", conclusion: "NOT_SUPPORTED", summary: "Late." }), response().response), /OPEN investigation/); assert.equal(await Refund.countDocuments(), 0); assert.equal(await LedgerEntry.countDocuments(), 0); });

test("DI-4 exposes complete safe state to admins and participant-specific outcomes without findings or finalizer identity", async () => { const f = await fixture(); await Dispute.updateOne({ _id: f.dispute._id }, { $set: { "customerInput.state": "CLOSED", "creatorInput.state": "CLOSED" } }); await addAdminDisputeFinding(req(f.admin, String(f.dispute._id), { subject: "BOTH", category: "OTHER", conclusion: "NOT_SUPPORTED", summary: "No support." }), response().response); await finalizeAdminDispute(req(f.admin, String(f.dispute._id), { customerOutcome: "ADVERSE_FINDING", customerSummary: "Customer internal", creatorOutcome: "NO_ADVERSE_FINDING", creatorSummary: "Creator internal", summary: "Safe summary", financialReviewRequired: true, governanceReviewRequired: true }), response().response); const adminRead = response(); await getAdminDisputeInvestigation({ params: { disputeId: String(f.dispute._id) }, query: {} } as unknown as Request, adminRead.response); const adminBody = adminRead.body as { findings: unknown[]; finalDecision: Record<string, unknown> }; assert.equal(adminBody.findings.length, 1); assert.equal(adminBody.finalDecision.customerOutcome, "ADVERSE_FINDING"); const customerRead = response(); await getBookingDisputeState({ params: { bookingId: String(f.booking._id) }, user: { id: String(f.customer._id) } } as unknown as Request, customerRead.response); const customerDecision = (customerRead.body as { dispute: { finalDecision: { outcome: string } } }).dispute.finalDecision; assert.equal(customerDecision.outcome, "ADVERSE_FINDING"); assert.equal(JSON.stringify(customerRead.body).includes("findings"), false); assert.equal(JSON.stringify(customerRead.body).includes(String(f.admin._id)), false); const creatorRead = response(); await getBookingDisputeState({ params: { bookingId: String(f.booking._id) }, user: { id: String(f.creator._id) } } as unknown as Request, creatorRead.response); const creatorDecision = (creatorRead.body as { dispute: { finalDecision: { outcome: string } } }).dispute.finalDecision; assert.equal(creatorDecision.outcome, "NO_ADVERSE_FINDING"); });
